
package gov.hhs.fha.nhinc.adapterdocretrieve;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import gov.hhs.fha.nhinc.common.nhinccommonadapter.RespondingGatewayCrossGatewayRetrieveRequestType;
import ihe.iti.xds_b._2007.RetrieveDocumentSetResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AdapterDocRetrievePortType", targetNamespace = "urn:gov:hhs:fha:nhinc:adapterdocretrieve")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    oasis.names.tc.ebxml_regrep.xsd.query._3.ObjectFactory.class,
    gov.hhs.fha.nhinc.common.subscriptionb2overridefordocuments.ObjectFactory.class,
    gov.hhs.fha.nhinc.common.subscriptionb2overrideforcdc.ObjectFactory.class,
    gov.hhs.fha.nhinc.common.nhinccommon.ObjectFactory.class,
    oasis.names.tc.ebxml_regrep.xsd.lcm._3.ObjectFactory.class,
    oasis.names.tc.xacml._2_0.context.schema.os.ObjectFactory.class,
    org.oasis_open.docs.wsrf.bf_2.ObjectFactory.class,
    org.xmlsoap.schemas.ws._2004._08.addressing.ObjectFactory.class,
    gov.hhs.fha.nhinc.common.nhinccommonadapter.ObjectFactory.class,
    org.oasis_open.docs.wsn.b_2.ObjectFactory.class,
    ihe.iti.xds_b._2007.ObjectFactory.class,
    com.services.nhinc.schema.auditmessage.ObjectFactory.class,
    oasis.names.tc.xacml._2_0.policy.schema.os.ObjectFactory.class,
    oasis.names.tc.ebxml_regrep.xsd.rs._3.ObjectFactory.class,
    gov.hhs.healthit.nhin.cdc.ObjectFactory.class,
    org.oasis_open.docs.wsn.t_1.ObjectFactory.class,
    oasis.names.tc.ebxml_regrep.xsd.rim._3.ObjectFactory.class
})
public interface AdapterDocRetrievePortType {


    /**
     * 
     * @param respondingGatewayCrossGatewayRetrieveRequest
     * @return
     *     returns ihe.iti.xds_b._2007.RetrieveDocumentSetResponseType
     */
    @WebMethod(operationName = "RespondingGateway_CrossGatewayRetrieve", action = "urn:RespondingGateway_CrossGatewayRetrieve")
    @WebResult(name = "RetrieveDocumentSetResponse", targetNamespace = "urn:ihe:iti:xds-b:2007", partName = "RespondingGateway_CrossGatewayRetrieveResponse")
    public RetrieveDocumentSetResponseType respondingGatewayCrossGatewayRetrieve(
        @WebParam(name = "RespondingGateway_CrossGatewayRetrieveRequest", targetNamespace = "urn:gov:hhs:fha:nhinc:common:nhinccommonadapter", partName = "RespondingGateway_CrossGatewayRetrieveRequest")
        RespondingGatewayCrossGatewayRetrieveRequestType respondingGatewayCrossGatewayRetrieveRequest);

}
