
package gov.hhs.fha.nhinc.adapterdocretrieve;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AdapterDocRetrieve", targetNamespace = "urn:gov:hhs:fha:nhinc:adapterdocretrieve", wsdlLocation = "file:/C:/Projects/NHINC/Current/Product/Production/Common/Interfaces/src/wsdl/AdapterDocRetrieve.wsdl")
public class AdapterDocRetrieve
    extends Service
{

    private final static URL ADAPTERDOCRETRIEVE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(gov.hhs.fha.nhinc.adapterdocretrieve.AdapterDocRetrieve.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = gov.hhs.fha.nhinc.adapterdocretrieve.AdapterDocRetrieve.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Projects/NHINC/Current/Product/Production/Common/Interfaces/src/wsdl/AdapterDocRetrieve.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Projects/NHINC/Current/Product/Production/Common/Interfaces/src/wsdl/AdapterDocRetrieve.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ADAPTERDOCRETRIEVE_WSDL_LOCATION = url;
    }

    public AdapterDocRetrieve(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdapterDocRetrieve() {
        super(ADAPTERDOCRETRIEVE_WSDL_LOCATION, new QName("urn:gov:hhs:fha:nhinc:adapterdocretrieve", "AdapterDocRetrieve"));
    }

    /**
     * 
     * @return
     *     returns AdapterDocRetrievePortType
     */
    @WebEndpoint(name = "AdapterDocRetrievePortSoap11")
    public AdapterDocRetrievePortType getAdapterDocRetrievePortSoap11() {
        return super.getPort(new QName("urn:gov:hhs:fha:nhinc:adapterdocretrieve", "AdapterDocRetrievePortSoap11"), AdapterDocRetrievePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdapterDocRetrievePortType
     */
    @WebEndpoint(name = "AdapterDocRetrievePortSoap11")
    public AdapterDocRetrievePortType getAdapterDocRetrievePortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("urn:gov:hhs:fha:nhinc:adapterdocretrieve", "AdapterDocRetrievePortSoap11"), AdapterDocRetrievePortType.class, features);
    }

}
