<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  Adapter Policy Engine WSDL
  -->
<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
   xmlns="http://schemas.xmlsoap.org/wsdl/" 
   xmlns:tns="urn:gov:hhs:fha:nhinc:adapterpolicyengine"
   xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
   xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" 
   xmlns:nccommonadapter="urn:gov:hhs:fha:nhinc:common:nhinccommonadapter"
   name="AdapterPolicyEngine" 
   targetNamespace="urn:gov:hhs:fha:nhinc:adapterpolicyengine">
  <documentation>Adapter Policy Engine</documentation>
  <types>
    <xsd:schema>
      <xsd:import namespace="urn:gov:hhs:fha:nhinc:common:nhinccommonadapter"
                  schemaLocation="../schemas/nhinc/common/NhincCommonAdapter.xsd"/>
    </xsd:schema>
  </types>
  
  <message name="CheckPolicyRequestMessage">
    <part name="CheckPolicyRequest" 
          element="nccommonadapter:CheckPolicyRequest"/>
  </message>
  <message name="CheckPolicyResponseMessage">
    <part name="CheckPolicyResponse" 
          element="nccommonadapter:CheckPolicyResponse"/>
  </message>
  
  <portType name="AdapterPolicyEnginePortType">
    <operation name="CheckPolicy">
      <input name="CheckPolicyRequest"
             message="tns:CheckPolicyRequestMessage" />
      <output name="CheckPolicyResponse"
              message="tns:CheckPolicyResponseMessage" />
    </operation>
  </portType>
  
  <binding name="AdapterPolicyEngineBindingSoap11" type="tns:AdapterPolicyEnginePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="CheckPolicy">
      <soap:operation soapAction="urn:CheckPolicy"/>
      <input name="CheckPolicyRequest">
        <soap:body use="literal"/>
      </input>
      <output name="CheckPolicyResponse">
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  
  <service name="AdapterPolicyEngine">
    <port name="AdapterPolicyEnginePortSoap11" 
          binding="tns:AdapterPolicyEngineBindingSoap11">
      <soap:address 
         location="http://localhost:${HttpDefaultPort}/NhinConnect/AdapterPolicyEngine" />
    </port>
  </service>
  <plnk:partnerLinkType name="AdapterPolicyEngine">
    <!-- A partner link type is automatically generated when a new port type is added. 
         Partner link types are used by BPEL processes. In a BPEL process, a partner 
         link represents the interaction between the BPEL process and a partner service. 
         Each partner link is associated with a partner link type. A partner link type 
         characterizes the conversational relationship between two services. The 
         partner link type can have one or two roles.-->
    <plnk:role name="AdapterPolicyEnginePortTypeRole" 
               portType="tns:AdapterPolicyEnginePortType"/>
  </plnk:partnerLinkType>
  
</definitions>
