<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  NHIN Cross Community Access (XCAD) WSDL defintions for Responding Gateway Query
  -->
<definitions xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ihe="urn:ihe:iti:xds-b:2007" xmlns:rs="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" xmlns:query="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsaws="http://www.w3.org/2005/08/addressing" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy" xmlns:sc="http://schemas.sun.com/2006/03/wss/server" xmlns:wspp="http://java.sun.com/xml/ns/wsit/policy" xmlns:dq="http://www.hhs.gov/healthit/nhin" name="XCA_RespondingGatewayDeferredResponse" targetNamespace="urn:ihe:iti:xds-b:2007">
    <documentation>NHIN Responding Gateway Query</documentation>
    <types>
        <xsd:schema xmlns:ns20="urn:gov:hhs:fha:nhinc:gateway:samltokendata">
            <xsd:import namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" schemaLocation="../schemas/ebRS/rs.xsd"/>
            <xsd:import namespace="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" schemaLocation="../schemas/ebRS/query.xsd"/>
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:gateway:samltokendata" schemaLocation="../schemas/nhinc/gateway/SamlTokenData.xsd"/>
            <xsd:import namespace="http://www.hhs.gov/healthit/nhin" schemaLocation="../schemas/nhin/QueryDocument.xsd"/>
        </xsd:schema>
    </types>
    <message name="CrossGatewayQuery_Message">
        <documentation>Cross Gateway Query</documentation>
        <part name="body" element="query:AdhocQueryResponse"/>
    </message>
    <message name="CrossGatewayQueryResponse_Message">
        <documentation>Cross Gateway Query Response</documentation>
        <part name="body" element="dq:DocQueryAcknowledgement"/>
    </message>
    <portType name="RespondingGateway_QueryDeferredResponse_PortType">
        <operation name="RespondingGateway_CrossGatewayQuery">
            <input message="ihe:CrossGatewayQuery_Message" wsaw:Action="urn:ihe:iti:2007:Deferred:CrossGatewayQueryResponse"/>
            <output message="ihe:CrossGatewayQueryResponse_Message" wsaw:Action="urn:ihe:iti:2007:CrossGatewayQueryAck"/>
        </operation>
    </portType>
    <binding name="RespondingGateway_QueryDeferredResponse_Binding_Soap" type="ihe:RespondingGateway_QueryDeferredResponse_PortType">
        <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsp:PolicyReference URI="#RespondingGateway_QueryDeferredResponse_Binding_SoapPolicy"/>
        <operation name="RespondingGateway_CrossGatewayQuery">
            <soap12:operation soapAction="urn:ihe:iti:2007:CrossGatewayQuery"/>
            <input>
                <soap12:body use="literal"/>
                <wsp:PolicyReference URI="#RespondingGateway_QueryDeferredResponse_Binding_Soap_Input_Policy"/>
            </input>
            <output>
                <soap12:body use="literal"/>
                <wsp:PolicyReference URI="#RespondingGateway_QueryDeferredResponse_Binding_Soap_Output_Policy"/>
            </output>
        </operation>
    </binding>
    <service name="RespondingGateway_QueryDeferredResponse_Service">
        <port name="RespondingGateway_QueryDeferredResponse_Port_Soap" binding="ihe:RespondingGateway_QueryDeferredResponse_Binding_Soap">
            <soap12:address location="https://localhost:${HttpsDefaultPort}/RespondingGateway_QueryDeferredResponse_Service"/>
        </port>
    </service>
    <wsp:Policy wsu:Id="RespondingGateway_QueryDeferredResponse_Binding_SoapPolicy">
        <wsp:ExactlyOne>
            <wsp:All>
                <sc:KeyStore wspp:visibility="private" aliasSelector="gov.hhs.fha.nhinc.callback.KeyStoreServerAliasSelector" callbackHandler="gov.hhs.fha.nhinc.callback.KeyStoreCallbackHandler"/>
                <sc:TrustStore wspp:visibility="private" callbackHandler="gov.hhs.fha.nhinc.callback.TrustStoreCallbackHandler"/>
                <sp:TransportBinding>
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken>
                                    <wsp:Policy>
                                        <sp:RequireClientCertificate/>
                                    </wsp:Policy>
                                </sp:HttpsToken>
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Strict/>
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp/>
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic256/>
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                    </wsp:Policy>
                </sp:TransportBinding>
                <sp:EndorsingSupportingTokens>
                    <wsp:Policy>
                        <sp:SamlToken sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                            <wsp:Policy>
                                <sp:WssSamlV20Token11/>
                            </wsp:Policy>
                        </sp:SamlToken>
                    </wsp:Policy>
                </sp:EndorsingSupportingTokens>
                <sp:Wss11>
                    <wsp:Policy>
                        <sp:MustSupportRefKeyIdentifier/>
                        <sp:MustSupportRefIssuerSerial/>
                        <sp:RequireSignatureConfirmation/>
                    </wsp:Policy>
                </sp:Wss11>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    <wsp:Policy wsu:Id="RespondingGateway_QueryDeferredResponse_Binding_Soap_Input_Policy">
        <wsp:ExactlyOne>
            <wsp:All>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    <wsp:Policy wsu:Id="RespondingGateway_QueryDeferredResponse_Binding_Soap_Output_Policy">
        <wsp:ExactlyOne>
            <wsp:All>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
</definitions>
