<?xml version="1.0" encoding="utf-8"?>
<definitions name="AdapterXDRRequest"
  targetNamespace="urn:gov:hhs:fha:nhinc:adapterxdrrequest"
  xmlns:tns="urn:gov:hhs:fha:nhinc:adapterxdrrequest"
  xmlns="http://schemas.xmlsoap.org/wsdl/"
  xmlns:nccommonadapter="urn:gov:hhs:fha:nhinc:common:nhinccommonadapter"
  xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:xdr="urn:ihe:iti:xdr:2007">
    <documentation>IHE Adapter Component for XDR Request</documentation>
    <types>
        <xsd:schema>
            <xsd:import namespace="urn:ihe:iti:xdr:2007"
                  schemaLocation="../schemas/nhinc/common/xdr.xsd"/>
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:common:nhinccommonadapter"
                        schemaLocation="../schemas/nhinc/common/NhincCommonAdapter.xsd"/>
        </xsd:schema>
    </types>
    <message name="AdapterXDRRequestInputMessage">
        <documentation>XDR Request Input Message</documentation>
        <part name="body" element="nccommonadapter:Adapter_ProvideAndRegisterDocumentSetRequest"/>
    </message>
    <message name="XDRRequestAcknowledgementMessage">
        <documentation>XDR Request Acknowledgement Message</documentation>
        <part name="body" element="xdr:Acknowledgement"/>
    </message>
  
    <portType name="AdapterXDRRequest_PortType">
        <operation name="ProvideAndRegisterDocumentSet-bRequest">
            <input message="tns:AdapterXDRRequestInputMessage"
        wsaw:Action="tns:XDRRequestInput"/>
            <output message="tns:XDRRequestAcknowledgementMessage"
        wsaw:Action="tns:XDRRequestAcknowledgement"/>
        </operation>
    </portType>

    <binding name="AdapterXDRRequest_Binding" type="tns:AdapterXDRRequest_PortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

        <operation name="ProvideAndRegisterDocumentSet-bRequest">
            <soap:operation soapAction="tns:ProvideAndRegisterDocumentSet-bRequest"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>

    <service name="AdapterXDRRequest_Service">
        <port name="AdapterXDRRequest_Port_Soap11" binding="tns:AdapterXDRRequest_Binding">
            <soap:address location="https://localhost:${HttpsDefaultPort}/AdapterXDRRequest"/>
        </port>
    </service>

</definitions>