<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="urn:gov:hhs:fha:nhinc:adaptercomponentmpi" xmlns:hl7="urn:hl7-org:v3" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" name="AdapterComponentMpi" targetNamespace="urn:gov:hhs:fha:nhinc:adaptercomponentmpi">
	<types>
		<xsd:schema targetNamespace="urn:gov:hhs:fha:nhinc:adaptercomponentmpi">
			<xsd:import namespace="urn:hl7-org:v3" schemaLocation="../schemas/nhinc/hl7/HL7PatientDiscoveryMessages.xsd"/>
			<xsd:import namespace="urn:hl7-org:v3" schemaLocation="../schemas/HL7V3/NE2008/multicacheschemas/PRPA_IN201306UV02.xsd"/>
			<xsd:import namespace="urn:hl7-org:v3" schemaLocation="../schemas/HL7V3/NE2008/multicacheschemas/PRPA_IN201305UV02.xsd"/>
		</xsd:schema>
	</types>
	<message name="FindCandidatesRequest">
		<part name="FindCandidatesRequest" element="hl7:PRPA_IN201305UV02"/>
	</message>
	<message name="FindCandidatesResponse">
		<part name="FindCandidatesResponse" element="hl7:PRPA_IN201306UV02"/>
	</message>
	<portType name="AdapterComponentMpiPortType">
		<operation name="FindCandidates">
			<input name="FindCandidatesRequest" message="tns:FindCandidatesRequest"/>
			<output name="FindCandidatesResponse" message="tns:FindCandidatesResponse"/>
		</operation>
	</portType>
	<binding name="AdapterComponentMpiPortTypeBinding" type="tns:AdapterComponentMpiPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="FindCandidates">
			<soap:operation soapAction="FindCandidates"/>
			<input name="FindCandidatesRequest">
				<soap:body use="literal"/>
			</input>
			<output name="FindCandidatesResponse">
				<soap:body use="literal"/>
			</output>
		</operation>
	</binding>
	<service name="AdapterComponentMpiService">
		<port name="AdapterComponentMpiPort" binding="tns:AdapterComponentMpiPortTypeBinding">
			<soap:address location="http://localhost:${NhincHttpPort}/NhinConnect/AdapterComponentMpiService"/>
		</port>
	</service>
	<plnk:partnerLinkType name="AdapterComponentMpi">
		<!-- A partner link type is automatically generated when a new port 
             type is added. Partner link types are used by BPEL processes. 
             In a BPEL process, a partner link represents the interaction 
             between the BPEL process and a partner service. Each partner 
             link is associated with a partner link type.  A partner link 
             type characterizes the conversational relationship between two 
             services. The partner link type can have one or two roles.-->
		<plnk:role name="MpiPortTypeRole" portType="tns:AdapterComponentMpiPortType"/>
	</plnk:partnerLinkType>
</definitions>
