<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  NHINC Proxy Document Query WSDL
  -->
<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/" 
   xmlns="http://schemas.xmlsoap.org/wsdl/" 
   xmlns:tns="urn:gov:hhs:fha:nhinc:nhincproxydocquery"
   xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
   xmlns:query="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" 
   xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" 
   xmlns:nccommonproxy="urn:gov:hhs:fha:nhinc:common:nhinccommonproxy"
   xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
   name="NhincProxyDocQuery" 
   targetNamespace="urn:gov:hhs:fha:nhinc:nhincproxydocquery">
  <documentation>Nhinc Proxy Document Query</documentation>
  <types>
    <xsd:schema>
      <xsd:import namespace="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" 
                  schemaLocation="../schemas/ebRS/query.xsd"/>
      <xsd:import namespace="urn:gov:hhs:fha:nhinc:common:nhinccommonproxy"
                  schemaLocation="../schemas/nhinc/common/NhincCommonProxy.xsd"/>
    </xsd:schema>
  </types>
  
  <message name="RespondingGateway_CrossGatewayQueryRequestMessage">
    <part name="RespondingGateway_CrossGatewayQueryRequest" 
          element="nccommonproxy:RespondingGateway_CrossGatewayQueryRequest"/>
  </message>
  <message name="RespondingGateway_CrossGatewayQueryResponseMessage">
    <part name="RespondingGateway_CrossGatewayQueryResponse" 
          element="query:AdhocQueryResponse"/>
  </message>
  
  <portType name="NhincProxyDocQueryPortType">
    <operation name="RespondingGateway_CrossGatewayQuery">
      <input name="RespondingGateway_CrossGatewayQueryRequest"
             message="tns:RespondingGateway_CrossGatewayQueryRequestMessage"
             wsaw:Action="urn:gov:hhs:fha:nhinc:nhincproxydocquery:RespondingGateway_CrossGatewayQueryRequestMessage"/>
      <output name="RespondingGateway_CrossGatewayQueryResponse"
              message="tns:RespondingGateway_CrossGatewayQueryResponseMessage"
              wsaw:Action="urn:gov:hhs:fha:nhinc:nhincproxydocquery:RespondingGateway_CrossGatewayQueryResponseMessage"/>
    </operation>
  </portType>
  
  <binding name="NhincProxyDocQueryBindingSoap" type="tns:NhincProxyDocQueryPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="RespondingGateway_CrossGatewayQuery">
      <soap:operation soapAction="urn:RespondingGateway_CrossGatewayQuery"/>
      <input name="RespondingGateway_CrossGatewayQueryRequest">
        <soap:body use="literal"/>
      </input>
      <output name="RespondingGateway_CrossGatewayQueryResponse">
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  
  <service name="NhincProxyDocQuery">
	<port name="NhincProxyDocQueryPortSoap" 
          binding="tns:NhincProxyDocQueryBindingSoap">
      <soap:address 
         location="http://localhost:${HttpDefaultPort}/NhinConnect/NhincProxyDocQuery" />
    </port>
  </service>
  <plnk:partnerLinkType name="NhincProxyDocQuery">
    <!-- A partner link type is automatically generated when a new port type is added. 
         Partner link types are used by BPEL processes. In a BPEL process, a partner 
         link represents the interaction between the BPEL process and a partner service. 
         Each partner link is associated with a partner link type. A partner link type 
         characterizes the conversational relationship between two services. The 
         partner link type can have one or two roles.-->
    <plnk:role name="NhincProxyDocQueryPortTypeRole" 
               portType="tns:NhincProxyDocQueryPortType"/>
  </plnk:partnerLinkType>
  
</definitions>
