<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:tns="urn:gov:hhs:fha:nhinc:entitypatientdiscoverysecuredasyncreq"
   xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
   xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
   xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
   xmlns:hl7="urn:hl7-org:v3"
   xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
   xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
   xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
   xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy"
   xmlns:sc="http://schemas.sun.com/2006/03/wss/server"
   xmlns:wspp="http://java.sun.com/xml/ns/wsit/policy" 
   name="EntityPatientDiscoverySecuredAsyncReq"
   targetNamespace="urn:gov:hhs:fha:nhinc:entitypatientdiscoverysecuredasyncreq">
    <wsdl:documentation>
     WSDL for Secured Entity interface for Patient Discovery Asychronous Requests
    </wsdl:documentation>
    <wsdl:types>
        <xsd:schema elementFormDefault="qualified"
                targetNamespace="urn:hl7-org:v3" xmlns:hl7="urn:hl7-org:v3">
      <!-- Include the message schema -->
            <xsd:include schemaLocation="../schemas/nhinc/hl7/HL7PatientDiscoveryMessages.xsd"/>
            <xsd:include schemaLocation="../schemas/HL7V3/NE2008/multicacheschemas/MCCI_IN000002UV01.xsd"/>
        </xsd:schema>  
    </wsdl:types>
    
    <wsdl:message name="ProcessPatientDiscoveryAsyncReqRequestMessage">
        <wsdl:part name="ProcessPatientDiscoveryAsyncReqAsyncRequest"
               element="hl7:RespondingGateway_PRPA_IN201305UV02SecuredRequest"/>
    </wsdl:message>
    <wsdl:message name="ProcessPatientDiscoveryAsyncReqResponseMessage">
        <wsdl:part name="ProcessPatientDiscoveryAsyncReqAsyncResponse"
               element="hl7:MCCI_IN000002UV01"/>
    </wsdl:message>

     <wsdl:portType name="EntityPatientDiscoverySecuredAsyncReqPortType">
        <wsdl:operation name="ProcessPatientDiscoveryAsyncReq">
            <wsdl:input name="ProcessPatientDiscoveryAsyncReqAsyncRequest"
                  message="tns:ProcessPatientDiscoveryAsyncReqRequestMessage"
                  wsaw:Action="urn:gov:hhs:fha:nhinc:entitypatientdiscoverysecuredasyncreq:ProcessPatientDiscoveryAsyncReqRequestMessage"/>
            <wsdl:output name="ProcessPatientDiscoveryAsyncReqAsyncResponse"
                   message="tns:ProcessPatientDiscoveryAsyncReqResponseMessage"
                   wsaw:Action="urn:gov:hhs:fha:nhinc:entitypatientdiscoverysecuredasyncreq:ProcessPatientDiscoveryAsyncReqResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="EntityPatientDiscoverySecuredAsyncReqBindingSoap"
                type="tns:EntityPatientDiscoverySecuredAsyncReqPortType">
        <soap12:binding style="document"
                     transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsp:PolicyReference URI="#Entity_PatientDiscovery_SoapPolicy"/>
        <wsdl:operation name="ProcessPatientDiscoveryAsyncReq">
            <soap12:operation soapAction="urn:ProcessPatientDiscoveryAsyncReq"/>
            <wsdl:input name="ProcessPatientDiscoveryAsyncReqAsyncRequest" >
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="ProcessPatientDiscoveryAsyncReqAsyncResponse" >
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="EntityPatientDiscoverySecuredAsyncReq">
        <wsdl:port name="EntityPatientDiscoverySecuredAsyncReqPortSoap"
               binding="tns:EntityPatientDiscoverySecuredAsyncReqBindingSoap">
            <soap12:address location="https://localhost/NhinConnect/EntityPatientDiscoverySecuredAsyncReq"/>
        </wsdl:port>
    </wsdl:service>

    <wsp:Policy wsu:Id="Entity_PatientDiscovery_SoapPolicy">
        <wsp:ExactlyOne>
            <wsp:All>
                <wsaws:UsingAddressing xmlns:wsaws="http://www.w3.org/2006/05/addressing/wsdl"/>
                <sc:KeyStore wspp:visibility="private"
                     aliasSelector="gov.hhs.fha.nhinc.callback.KeyStoreServerAliasSelector"
                     callbackHandler="gov.hhs.fha.nhinc.callback.KeyStoreCallbackHandler"/>
                <sc:TrustStore wspp:visibility="private"
                       callbackHandler="gov.hhs.fha.nhinc.callback.TrustStoreCallbackHandler"/>
                <sp:TransportBinding>
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken>
                                    <wsp:Policy>
                                        <sp:RequireClientCertificate/>
                                    </wsp:Policy>
                                </sp:HttpsToken>
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Strict/>
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp/>
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128/>
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                    </wsp:Policy>
                </sp:TransportBinding>
                <sp:EndorsingSupportingTokens>
                    <wsp:Policy>
                        <sp:SamlToken
                sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                            <wsp:Policy>
                                <sp:WssSamlV20Token11/>
                            </wsp:Policy>
                        </sp:SamlToken>
                    </wsp:Policy>
                </sp:EndorsingSupportingTokens>
                <sp:Wss11>
                    <wsp:Policy>
                        <sp:MustSupportRefKeyIdentifier/>
                        <sp:MustSupportRefIssuerSerial/>
                        <sp:RequireSignatureConfirmation/>
                    </wsp:Policy>
                </sp:Wss11>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
</wsdl:definitions>

