<?xml version="1.0" encoding="UTF-8"?>
<!--
  Entity Performance Log Query WSDL
  -->
<definitions name="EntityPerformanceLogQuery" 
    targetNamespace="urn:gov:hhs:fha:nhinc:entityperformancelogquery"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:tns="urn:gov:hhs:fha:nhinc:entityperformancelogquery" 
    xmlns:perf="urn:gov:hhs:fha:nhinc:common:entityperformancelogquery" 
    xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" 
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/"
    >
    <documentation>Entity Performance Log Query WSDL</documentation>
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/EntityPerformanceLogQuery">
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:common:entityperformancelogquery" schemaLocation="../schemas/nhinc/common/EntityPerformanceLogQuery.xsd"/>
        </xsd:schema>
    </types>

    <message name="EntityPerformanceLogQueryRequestMessage">
        <part name="EntityPerformanceLogQueryRequest" element="perf:EntityPerformanceLogQueryRequest"/>
    </message>
    <message name="EntityPerformanceLogQueryResponseMessage">
        <part name="EntityPerformanceLogQueryResponse" element="perf:EntityPerformanceLogQueryResponse"/>
    </message>
    
    <portType name="EntityPerformanceLogQueryPortType">
        <operation name="FindPerformanceData">
            <input name="FindPerformanceDataRequest" message="tns:EntityPerformanceLogQueryRequestMessage"/>
            <output name="FindPerformanceDataResponse" message="tns:EntityPerformanceLogQueryResponseMessage"/>
        </operation>
    </portType>
    
    <binding name="EntityPerformanceLogQueryBinding" type="tns:EntityPerformanceLogQueryPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="FindPerformanceData">
            <soap:operation soapAction="urn:FindPerformanceData"/>
            <input name="FindPerformanceDataRequest">
                <soap:body use="literal"/>
            </input>
            <output name="FindPerformanceDataResponse">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    
    <service name="EntityPerformanceLogQuery">
        <port name="EntityPerformanceLogQueryPort" binding="tns:EntityPerformanceLogQueryBinding">
            <soap:address location="http://localhost:${NhincHttpPort}/NhinConnect/EntityPerformanceLogQuery"/>
        </port>
    </service>
    
    <plnk:partnerLinkType name="EntityPerformanceLogQuery">
        <!-- A partner link type is automatically generated when a new port 
             type is added. Partner link types are used by BPEL processes. 
             In a BPEL process, a partner link represents the interaction 
             between the BPEL process and a partner service. Each partner 
             link is associated with a partner link type.  A partner link 
             type characterizes the conversational relationship between two 
             services. The partner link type can have one or two roles.-->
        <plnk:role name="EntityPerformanceLogQueryPortTypeRole" portType="tns:EntityPerformanceLogQueryPortType"/>
    </plnk:partnerLinkType>
</definitions>
