<?xml version="1.0" encoding="UTF-8"?>
<definitions name="SamlReceive" targetNamespace="http://j2ee.netbeans.org/wsdl/Interfaces/SamlReceive"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:tns="http://j2ee.netbeans.org/wsdl/Interfaces/SamlReceive" 
    xmlns:ns="urn:gov:hhs:fha:nhinc:common:nhinccommon" 
    xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" 
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
    xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" 
    xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" 
    xmlns:wsaws="http://www.w3.org/2005/08/addressing" 
    xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy" 
    xmlns:sc="http://schemas.sun.com/2006/03/wss/server" 
    xmlns:wspp="http://java.sun.com/xml/ns/wsit/policy">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/Interfaces/SamlReceive">
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon" schemaLocation="../schemas/nhinc/common/NhincCommon.xsd"/>
        </xsd:schema>
    </types>
    <message name="SamlReceiveOperationRequest">
        <part name="body" element="ns:Request"/>
    </message>
    <message name="SamlReceiveOperationResponse">
        <part name="ack" element="ns:Acknowledgement"/>
    </message>
    <portType name="SamlReceivePortType">
        <operation name="SamlReceiveOperation">
            <input name="input1" message="tns:SamlReceiveOperationRequest"/>
            <output name="output1" message="tns:SamlReceiveOperationResponse"/>
        </operation>
    </portType>
    <binding name="SamlReceiveBinding" type="tns:SamlReceivePortType">
        <wsp:PolicyReference URI="#SamlReceiveBindingPolicy"/>
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="SamlReceiveOperation">
            <soap:operation soapAction="SamlReceiveOperation"/>
            <input name="input1">
                <soap:body use="literal"/>
                <wsp:PolicyReference URI="#SamlReceiveBinding_input1_Policy"/>
            </input>
            <output name="output1">
                <soap:body use="literal"/>
                <wsp:PolicyReference URI="#SamlReceiveBinding_output1_Policy"/>
            </output>
        </operation>
    </binding>
    <service name="SamlReceiveService">
        <port name="SamlReceivePort" binding="tns:SamlReceiveBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/SamlReceiveService/SamlReceivePort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="SamlReceive">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="SamlReceivePortTypeRole" portType="tns:SamlReceivePortType"/>
    </plnk:partnerLinkType>
    <wsp:Policy wsu:Id="SamlReceiveBindingPolicy">
        <wsp:ExactlyOne>
            <wsp:All>
                <wsaws:UsingAddressing xmlns:wsaws="http://www.w3.org/2006/05/addressing/wsdl"/>
                <sc:KeyStore wspp:visibility="private" 
                     aliasSelector="gov.hhs.fha.nhinc.callback.KeyStoreServerAliasSelector" 
                     callbackHandler="gov.hhs.fha.nhinc.callback.KeyStoreCallbackHandler"/>
                <sc:TrustStore wspp:visibility="private" 
                       callbackHandler="gov.hhs.fha.nhinc.callback.TrustStoreCallbackHandler"/>
                <sp:TransportBinding>
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken>
                                    <wsp:Policy>
                                        <sp:RequireClientCertificate/>
                                    </wsp:Policy>
                                </sp:HttpsToken>
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Strict/>
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp/>
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128/>
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                    </wsp:Policy>
                </sp:TransportBinding>
                <sp:EndorsingSupportingTokens>
                    <wsp:Policy>
                        <sp:SamlToken 
                sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                            <wsp:Policy>
                                <sp:WssSamlV20Token11/>
                            </wsp:Policy>
                        </sp:SamlToken>
                    </wsp:Policy>
                </sp:EndorsingSupportingTokens>
                <sp:Wss11>
                    <wsp:Policy>
                        <sp:MustSupportRefKeyIdentifier/>
                        <sp:MustSupportRefIssuerSerial/>
                        <sp:RequireSignatureConfirmation/>
                    </wsp:Policy>
                </sp:Wss11>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    <wsp:Policy wsu:Id="SamlReceiveBinding_input1_Policy">
        <wsp:ExactlyOne>
            <wsp:All>
                <!--<sp:EncryptedParts>
                    <sp:Body/>
                </sp:EncryptedParts>
                <sp:SignedParts>
                    <sp:Body/>
                    <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing"/>
                    <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing"/>
                    <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing"/>
                    <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing"/>
                    <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing"/>
                    <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing"/>
                    <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing"/>
                    <sp:Header Name="AckRequested" Namespace="http://schemas.xmlsoap.org/ws/2005/02/rm"/>
                    <sp:Header Name="SequenceAcknowledgement" Namespace="http://schemas.xmlsoap.org/ws/2005/02/rm"/>
                    <sp:Header Name="Sequence" Namespace="http://schemas.xmlsoap.org/ws/2005/02/rm"/>
                </sp:SignedParts> -->
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    <wsp:Policy wsu:Id="SamlReceiveBinding_output1_Policy">
        <wsp:ExactlyOne>
            <wsp:All>
               <!-- <sp:EncryptedParts>
                    <sp:Body/>
                </sp:EncryptedParts>
                <sp:SignedParts>
                    <sp:Body/>
                    <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing"/>
                    <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing"/>
                    <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing"/>
                    <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing"/>
                    <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing"/>
                    <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing"/>
                    <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing"/>
                    <sp:Header Name="AckRequested" Namespace="http://schemas.xmlsoap.org/ws/2005/02/rm"/>
                    <sp:Header Name="SequenceAcknowledgement" Namespace="http://schemas.xmlsoap.org/ws/2005/02/rm"/>
                    <sp:Header Name="Sequence" Namespace="http://schemas.xmlsoap.org/ws/2005/02/rm"/>
                </sp:SignedParts>-->
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
</definitions>
