<?xml version="1.0" encoding="utf-8"?>
<definitions name="AdapterXDRResponse"
  targetNamespace="urn:gov:hhs:fha:nhinc:adapterxdrresponse"
  xmlns:tns="urn:gov:hhs:fha:nhinc:adapterxdrresponse"
  xmlns="http://schemas.xmlsoap.org/wsdl/"
  xmlns:nccommonadapter="urn:gov:hhs:fha:nhinc:common:nhinccommonadapter"
  xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:xdr="urn:ihe:iti:xdr:2007">
  <documentation>IHE Adapter Component for XDR Response</documentation>
  <types>
    <xsd:schema>
      <xsd:import namespace="urn:ihe:iti:xdr:2007"
                  schemaLocation="../schemas/nhinc/common/xdr.xsd"/>
      <xsd:import namespace="urn:gov:hhs:fha:nhinc:common:nhinccommonadapter"
                  schemaLocation="../schemas/nhinc/common/NhincCommonAdapter.xsd"/>
    </xsd:schema>
  </types>

  <message name="AdapterXDRResponseInputMessage">
    <documentation>XDR Response Input Message</documentation>
    <part name="body" element="nccommonadapter:AdapterRegistryResponse"/>
  </message>
  <message name="XDRResponseAcknowledgementMessage">
    <documentation>XDR Response Acknowledgement Message</documentation>
    <part name="body" element="xdr:Acknowledgement"/>
  </message>

  <portType name="AdapterXDRResponse_PortType">
    <operation name="ProvideAndRegisterDocumentSet-bResponse">
      <input message="tns:AdapterXDRResponseInputMessage"
        wsaw:Action="tns:XDRResponseInput"/>
      <output message="tns:XDRResponseAcknowledgementMessage"
        wsaw:Action="tns:XDRResponseAcknowledgement"/>
    </operation>
  </portType>


  <binding name="AdapterXDRResponse_Binding" type="tns:AdapterXDRResponse_PortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="ProvideAndRegisterDocumentSet-bResponse">
      <soap:operation soapAction="tns:ProvideAndRegisterDocumentSet-bResponse"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>

  <service name="AdapterXDRResponse_Service">
    <port name="AdapterXDRResponse_Port_Soap11" binding="tns:AdapterXDRResponse_Binding">
      <soap:address location="https://localhost:${HttpsDefaultPort}/AdapterXDRResponseService"/>
    </port>  
  </service>
</definitions>