copy C:\projects\NHINC\3.1\Product\Production\Gateway\CONNECTLiFTServerApp\dist\debug\CONNECTLiFTServerApp.jar .
copy C:\projects\NHINC\3.1\ThirdParty\log4j\commons-logging-1.1.1.jar .
copy C:\projects\NHINC\3.1\Product\Production\Common\CONNECTCoreLib\dist\debug\CONNECTCoreLib.jar .
copy C:\projects\NHINC\3.1\Product\Production\Common\CONNECTCommonTypesLib\dist\debug\CONNECTCommonTypesLib.jar .
copy C:\projects\NHINC\3.1\ThirdParty\log4j\log4j-1.2.15.jar .
copy C:\projects\NHINC\3.1\ThirdParty\HibernateLibraries\antlr-2.7.6.jar .
copy C:\projects\NHINC\3.1\ThirdParty\HibernateLibraries\asm.jar .
copy C:\projects\NHINC\3.1\ThirdParty\HibernateLibraries\asm-attrs.jar .
copy C:\projects\NHINC\3.1\ThirdParty\HibernateLibraries\cglib-2.1.3.jar .
copy C:\projects\NHINC\3.1\ThirdParty\HibernateLibraries\commons-collections-2.1.1.jar .
copy C:\projects\NHINC\3.1\ThirdParty\HibernateLibraries\dom4j-1.6.1.jar .
copy C:\projects\NHINC\3.1\ThirdParty\HibernateLibraries\ehcache-1.2.3.jar .
copy C:\projects\NHINC\3.1\ThirdParty\HibernateLibraries\hibernate3.jar .
copy C:\projects\NHINC\3.1\ThirdParty\HibernateLibraries\jdbc2_0-stdext.jar .
copy C:\projects\NHINC\3.1\ThirdParty\HibernateLibraries\jta.jar .
copy C:\projects\NHINC\3.1\ThirdParty\MySQLDB\mysql-connector-java-5.1.8-bin.jar .
copy C:\projects\NHINC\3.1\ThirdParty\C3PO\c3p0-0.9.1.2.jar .
copy C:\projects\NHINC\3.1\ThirdParty\Metro\webservices-rt.jar .
