<?xml version="1.0" encoding="utf-8"?>
<!-- This wsdl file is for an XDS.b Document Repository Actor -->
<definitions name="NhincProxyXDRResponse"
  targetNamespace="urn:gov:hhs:fha:nhinc:nhincproxyxdr:async:response"
  xmlns:tns="urn:gov:hhs:fha:nhinc:nhincproxyxdr:async:response"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
  xmlns="http://schemas.xmlsoap.org/wsdl/"
  xmlns:nccommonproxy="urn:gov:hhs:fha:nhinc:common:nhinccommonproxy"
  xmlns:ihe="urn:ihe:iti:xds-b:2007"
  xmlns:rs="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0"
  xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"   
  xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:xdr="urn:ihe:iti:xdr:2007"
  >
    <documentation>IHE XDR Document Repository</documentation>
    <types>
        <xsd:schema>
            <xsd:import namespace="urn:ihe:iti:xdr:2007"
                  schemaLocation="../schemas/nhinc/common/xdr.xsd"/>
            <xsd:import namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0"
                  schemaLocation="../schemas/ebRS/rs.xsd"/>
            <xsd:import namespace="urn:ihe:iti:xds-b:2007"
                  schemaLocation="../schemas/ihe/XDS.b_DocumentRepository.xsd"/>
            <xsd:import namespace="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0"
                  schemaLocation="../schemas/ebRS/query.xsd"/>
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:gateway:samltokendata"
                  schemaLocation="../schemas/nhinc/gateway/SamlTokenData.xsd"/>
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:common:nhinccommonproxy"
                  schemaLocation="../schemas/nhinc/common/NhincCommonProxy.xsd"/>
        </xsd:schema>

    </types>
    <message name="ProvideAndRegisterDocumentSet-bResponse_RequestMessage">
        <documentation>Provide and Register Document Set Response - Request</documentation>
        <part name="ProvideAndRegisterResponseRequest" element="nccommonproxy:RespondingGateway_ProvideAndRegisterDocumentSetResponseRequest"/>
    </message>
    <message name="ProvideAndRegisterDocumentSet-bResponse_ResponseMessage">
        <documentation>Provide And Register Document Set Response - Response</documentation>
        <part name="ProvideAndRegisterResponseResponse" element="xdr:Acknowledgement"/>
    </message>
    <portType name="ProxyXDRResponse_PortType">
        <operation name="ProvideAndRegisterDocumentSet-bResponse">
            <input message="tns:ProvideAndRegisterDocumentSet-bResponse_RequestMessage"
        wsaw:Action="tns:ProvideAndRegisterDocumentSet-bResponse_Request"/>
            <output message="tns:ProvideAndRegisterDocumentSet-bResponse_ResponseMessage"
        wsaw:Action="tns:ProvideAndRegisterDocumentSet-bResponse_Response"/>
        </operation>
    </portType>
    <binding name="ProxyXDRResponse_Binding" type="tns:ProxyXDRResponse_PortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="ProvideAndRegisterDocumentSet-bResponse">
            <soap:operation soapAction="tns:ProvideAndRegisterDocumentSet-bResponse"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>

    </binding>
    <service name="ProxyXDRResponse_Service">
        <port name="ProxyXDRResponse_Port" binding="tns:ProxyXDRResponse_Binding">
            <soap:address location="http://localhost:${HttpDefaultPort}/EntityService/NhincProxyXDRResponse"/>
        </port>
    </service>
</definitions>



