<?xml version="1.0" encoding="UTF-8"?>
<!--
  Adapter Patient Discovery Async Req Queue Process WSDL
  -->
<definitions name="AdapterDocQueryDeferredReqQueueProcess"
    targetNamespace="urn:gov:hhs:fha:nhinc:adapterdocqueryreqqueueprocess"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:tns="urn:gov:hhs:fha:nhinc:adapterdocqueryreqqueueprocess"
    xmlns:reqq="urn:gov:hhs:fha:nhinc:gateway:adapterdocqueryreqqueueprocess"
    xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/"
    >

    <documentation>
     WSDL for Adapter interface of Query For Documents Deferred Req Queue Process
    </documentation>

    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/AdapterDocQueryDeferredReqQueueProcess">
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:gateway:adapterdocqueryreqqueueprocess" schemaLocation="../schemas/nhinc/gateway/AdapterDocQueryDeferredReqQueueProcess.xsd"/>
        </xsd:schema>
    </types>

    <message name="DocQueryDeferredReqQueueProcessRequestMessage">
        <part name="parameters" element="reqq:DocQueryDeferredReqQueueProcessRequest"/>
    </message>

    <message name="DocQueryDeferredReqQueueProcessResponseMessage">
        <part name="parameters" element="reqq:DocQueryDeferredReqQueueProcessResponse"/>
    </message>

    <portType name="AdapterDocQueryDeferredReqQueueProcessPortType">
        <operation name="ProcessDocQueryDeferredReqQueue">
            <input name="ProcessDocQueryDeferredReqQueueRequest" message="tns:DocQueryDeferredReqQueueProcessRequestMessage"/>
            <output name="ProcessDocQueryDeferredReqQueueResponse" message="tns:DocQueryDeferredReqQueueProcessResponseMessage"/>
        </operation>
    </portType>

    <binding name="AdapterDocQueryDeferredReqQueueProcessBindingSoap" type="tns:AdapterDocQueryDeferredReqQueueProcessPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="ProcessDocQueryDeferredReqQueue">
            <soap:operation soapAction="urn:ProcessDocQueryDeferredReqQueue"/>
            <input name="ProcessDocQueryDeferredReqQueueRequest">
                <soap:body use="literal"/>
            </input>
            <output name="ProcessDocQueryDeferredReqQueueResponse">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>

    <service name="AdapterDocQueryDeferredReqQueueProcess">
        <port name="AdapterDocQueryDeferredReqQueueProcessPort" binding="tns:AdapterDocQueryDeferredReqQueueProcessBindingSoap">
            <soap:address location="http://localhost:${NhincHttpPort}/CONNECTAdapter/AdapterDocQueryDeferredReqQueueProcess"/>
        </port>
    </service>

    <plnk:partnerLinkType name="AdapterDocQueryDeferredReqQueueProcess">
        <!-- A partner link type is automatically generated when a new port 
             type is added. Partner link types are used by BPEL processes. 
             In a BPEL process, a partner link represents the interaction 
             between the BPEL process and a partner service. Each partner 
             link is associated with a partner link type.  A partner link 
             type characterizes the conversational relationship between two 
             services. The partner link type can have one or two roles.-->
        <plnk:role name="AdapterDocQueryDeferredReqQueueProcessPortTypeRole" portType="tns:AdapterDocQueryDeferredReqQueueProcessPortType"/>
    </plnk:partnerLinkType>
</definitions>
