
package gov.hhs.fha.nhinc.adapterdocquery;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AdapterDocQuery", targetNamespace = "urn:gov:hhs:fha:nhinc:adapterdocquery", wsdlLocation = "file:/C:/Projects/NHINC/Current/Product/Production/Common/Interfaces/src/wsdl/AdapterDocQuery.wsdl")
public class AdapterDocQuery
    extends Service
{

    private final static URL ADAPTERDOCQUERY_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(gov.hhs.fha.nhinc.adapterdocquery.AdapterDocQuery.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = gov.hhs.fha.nhinc.adapterdocquery.AdapterDocQuery.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Projects/NHINC/Current/Product/Production/Common/Interfaces/src/wsdl/AdapterDocQuery.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Projects/NHINC/Current/Product/Production/Common/Interfaces/src/wsdl/AdapterDocQuery.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ADAPTERDOCQUERY_WSDL_LOCATION = url;
    }

    public AdapterDocQuery(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdapterDocQuery() {
        super(ADAPTERDOCQUERY_WSDL_LOCATION, new QName("urn:gov:hhs:fha:nhinc:adapterdocquery", "AdapterDocQuery"));
    }

    /**
     * 
     * @return
     *     returns AdapterDocQueryPortType
     */
    @WebEndpoint(name = "AdapterDocQueryPortSoap11")
    public AdapterDocQueryPortType getAdapterDocQueryPortSoap11() {
        return super.getPort(new QName("urn:gov:hhs:fha:nhinc:adapterdocquery", "AdapterDocQueryPortSoap11"), AdapterDocQueryPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdapterDocQueryPortType
     */
    @WebEndpoint(name = "AdapterDocQueryPortSoap11")
    public AdapterDocQueryPortType getAdapterDocQueryPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("urn:gov:hhs:fha:nhinc:adapterdocquery", "AdapterDocQueryPortSoap11"), AdapterDocQueryPortType.class, features);
    }

}
