
package gov.hhs.fha.nhinc.adapterdocquery;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import gov.hhs.fha.nhinc.common.nhinccommonadapter.RespondingGatewayCrossGatewayQueryRequestType;
import oasis.names.tc.ebxml_regrep.xsd.query._3.AdhocQueryResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AdapterDocQueryPortType", targetNamespace = "urn:gov:hhs:fha:nhinc:adapterdocquery")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    oasis.names.tc.xacml._2_0.policy.schema.os.ObjectFactory.class,
    org.oasis_open.docs.wsn.b_2.ObjectFactory.class,
    oasis.names.tc.ebxml_regrep.xsd.rs._3.ObjectFactory.class,
    org.oasis_open.docs.wsn.t_1.ObjectFactory.class,
    org.xmlsoap.schemas.ws._2004._08.addressing.ObjectFactory.class,
    oasis.names.tc.ebxml_regrep.xsd.query._3.ObjectFactory.class,
    gov.hhs.fha.nhinc.common.subscriptionb2overridefordocuments.ObjectFactory.class,
    oasis.names.tc.ebxml_regrep.xsd.lcm._3.ObjectFactory.class,
    oasis.names.tc.xacml._2_0.context.schema.os.ObjectFactory.class,
    com.services.nhinc.schema.auditmessage.ObjectFactory.class,
    org.oasis_open.docs.wsrf.bf_2.ObjectFactory.class,
    gov.hhs.healthit.nhin.cdc.ObjectFactory.class,
    oasis.names.tc.ebxml_regrep.xsd.rim._3.ObjectFactory.class,
    ihe.iti.xds_b._2007.ObjectFactory.class,
    gov.hhs.fha.nhinc.common.subscriptionb2overrideforcdc.ObjectFactory.class,
    gov.hhs.fha.nhinc.common.nhinccommon.ObjectFactory.class,
    gov.hhs.fha.nhinc.common.nhinccommonadapter.ObjectFactory.class
})
public interface AdapterDocQueryPortType {


    /**
     * 
     * @param respondingGatewayCrossGatewayQueryRequest
     * @return
     *     returns oasis.names.tc.ebxml_regrep.xsd.query._3.AdhocQueryResponse
     */
    @WebMethod(operationName = "RespondingGateway_CrossGatewayQuery", action = "urn:RespondingGateway_CrossGatewayQuery")
    @WebResult(name = "AdhocQueryResponse", targetNamespace = "urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0", partName = "RespondingGateway_CrossGatewayQueryResponse")
    public AdhocQueryResponse respondingGatewayCrossGatewayQuery(
        @WebParam(name = "RespondingGateway_CrossGatewayQueryRequest", targetNamespace = "urn:gov:hhs:fha:nhinc:common:nhinccommonadapter", partName = "RespondingGateway_CrossGatewayQueryRequest")
        RespondingGatewayCrossGatewayQueryRequestType respondingGatewayCrossGatewayQueryRequest);

}
