<?xml version="1.0" encoding="utf-8"?>
<!-- This wsdl file is for an XDS.b Document Registry Actor -->
<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
  xmlns:edxlde="urn:oasis:names:tc:emergency:EDXL:DE:1.0"
	xmlns="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="urn:gov:hhs:fha:nhinc:nhincadmindistribution"
  xmlns:tns="urn:gov:hhs:fha:nhinc:nhincadmindistribution"
	xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
	xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" 
	xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy" 
	xmlns:sc="http://schemas.sun.com/2006/03/wss/server" 
	xmlns:wspp="http://java.sun.com/xml/ns/wsit/policy" 
	xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
	xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" 
	xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
	xmlns:nccommonproxy="urn:gov:hhs:fha:nhinc:common:nhinccommonproxy"
	name="NhincAdministrativeDistribution">
    <documentation>NHIN Administrative Distribution wsdl</documentation>
    <types>
        <xsd:schema>
            <xsd:import namespace="urn:oasis:names:tc:emergency:EDXL:DE:1.0" schemaLocation="../schemas/ebRS/edxl-de.xsd"/>
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:common:nhinccommonproxy" schemaLocation="../schemas/nhinc/common/NhincCommonProxy.xsd"/>
        </xsd:schema>
    </types>
    <message name="SendAlertMessage_Message">
        <documentation>Send Alert Message</documentation>
        <part name="body" element="nccommonproxy:RespondingGateway_SendAlertMessage"/>
    </message>
    <portType name="NhincAdminDist_PortType">
        <operation name="SendAlertMessage">
            <input message="tns:SendAlertMessage_Message"
		wsaw:Action="urn:gov:hhs:fha:nhinc:nhincadmindistribution:SendAlertMessage_Message"/>
        </operation>
    </portType>
    <binding name="NhincAdminDist_Binding_Soap12" type="tns:NhincAdminDist_PortType">
        <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="SendAlertMessage">
            <soap12:operation soapAction="urn:oasis:names:tc:emergency:EDXL:DE:1.0:SendAlertMessage"/>
            <input>
                <soap12:body use="literal"/>
            </input>
        </operation>
    </binding>
    <service name="NhincAdminDistService">
        <port name="NhincAdminDist_PortType" binding="tns:NhincAdminDist_Binding_Soap12">
            <soap12:address location="http://localhost:${HttpDefaultPort}/NhinConnect/NhincAdminDistService"/>
        </port>
    </service>
    

</definitions>

