<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="NhinSubscriptionWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/NhinSubscriptionWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/NhinSubscriptionWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://docs.oasis-open.org/wsn/bw-2">
    <import location="Interfaces/wsdl/NhinSubscription.wsdl" namespace="http://docs.oasis-open.org/wsn/bw-2"/>
    <plnk:partnerLinkType name="NotificationConsumerLinkType">
        <plnk:role name="NotificationProducerRole" portType="ns:NotificationProducer"/>
    </plnk:partnerLinkType>
    <plnk:partnerLinkType name="NotificationSubscriptionManagerLinkType">
        <plnk:role name="NotificationSubscriptionManagerRole" portType="ns:SubscriptionManager"/>
    </plnk:partnerLinkType>
    <plnk:partnerLinkType name="NotificationLinkType">
        <plnk:role name="NotificationConsumerRole" portType="ns:NotificationConsumer"/>
    </plnk:partnerLinkType>
</definitions>
