copy C:\projects\NHINC\Current\Product\Production\Gateway\LiFTServerApp\dist\debug\LiFTServerApp.jar .
copy C:\projects\NHINC\Current\Product\Production\Gateway\NhincGatewayLib\dist\debug\NhincGatewayLib.jar .
copy C:\projects\NHINC\Current\Product\Production\Gateway\NhincGatewayDAO\dist\debug\NhincGatewayDAO.jar .
copy C:\projects\NHINC\Current\ThirdParty\log4j\commons-logging-1.1.1.jar .
copy C:\projects\NHINC\Current\Product\Production\Common\NhincCommonLib\dist\debug\NhincCommonLib.jar .
copy C:\projects\NHINC\Current\Product\Production\Common\NhincCommonTypesLib\dist\debug\NhincCommonTypesLib.jar .
copy C:\projects\NHINC\Current\ThirdParty\log4j\log4j-1.2.15.jar .
copy C:\projects\NHINC\Current\ThirdParty\HibernateLibraries\antlr-2.7.6.jar .
copy C:\projects\NHINC\Current\ThirdParty\HibernateLibraries\asm.jar .
copy C:\projects\NHINC\Current\ThirdParty\HibernateLibraries\asm-attrs.jar .
copy C:\projects\NHINC\Current\ThirdParty\HibernateLibraries\cglib-2.1.3.jar .
copy C:\projects\NHINC\Current\ThirdParty\HibernateLibraries\commons-collections-2.1.1.jar .
copy C:\projects\NHINC\Current\ThirdParty\HibernateLibraries\dom4j-1.6.1.jar .
copy C:\projects\NHINC\Current\ThirdParty\HibernateLibraries\ehcache-1.2.3.jar .
copy C:\projects\NHINC\Current\ThirdParty\HibernateLibraries\hibernate3.jar .
copy C:\projects\NHINC\Current\ThirdParty\HibernateLibraries\jdbc2_0-stdext.jar .
copy C:\projects\NHINC\Current\ThirdParty\HibernateLibraries\jta.jar .
copy C:\projects\NHINC\Current\ThirdParty\MySQLDB\mysql-connector-java-5.1.8-bin.jar .
copy C:\projects\NHINC\Current\ThirdParty\C3PO\c3p0-0.9.1.2.jar .