<?xml version="1.0" encoding="UTF-8"?>
<!--
  Adapter Patient Discovery Async Req Queue Process WSDL
  -->
<definitions name="AdapterPatientDiscoveryDeferredReqQueueProcess"
    targetNamespace="urn:gov:hhs:fha:nhinc:adapterpatientdiscoveryreqqueueprocess"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:tns="urn:gov:hhs:fha:nhinc:adapterpatientdiscoveryreqqueueprocess"
    xmlns:reqq="urn:gov:hhs:fha:nhinc:gateway:adapterpatientdiscoveryreqqueueprocess"
    xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/"
    >

    <documentation>
     WSDL for Adapter interface of Patient Discovery Async Req Queue Process
    </documentation>

    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/AdapterPatientDiscoveryDeferredReqQueueProcess">
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:gateway:adapterpatientdiscoveryreqqueueprocess" schemaLocation="../schemas/nhinc/gateway/AdapterPatientDiscoveryDeferredReqQueueProcess.xsd"/>
        </xsd:schema>
    </types>

    <message name="PatientDiscoveryDeferredReqQueueProcessRequestMessage">
        <part name="parameters" element="reqq:PatientDiscoveryDeferredReqQueueProcessRequest"/>
    </message>

    <message name="PatientDiscoveryDeferredReqQueueProcessResponseMessage">
        <part name="parameters" element="reqq:PatientDiscoveryDeferredReqQueueProcessResponse"/>
    </message>

    <portType name="AdapterPatientDiscoveryDeferredReqQueueProcessPortType">
        <operation name="ProcessPatientDiscoveryDeferredReqQueue">
            <input name="ProcessPatientDiscoveryDeferredReqQueueRequest" message="tns:PatientDiscoveryDeferredReqQueueProcessRequestMessage"/>
            <output name="ProcessPatientDiscoveryDeferredReqQueueResponse" message="tns:PatientDiscoveryDeferredReqQueueProcessResponseMessage"/>
        </operation>
    </portType>

    <binding name="AdapterPatientDiscoveryDeferredReqQueueProcessBindingSoap" type="tns:AdapterPatientDiscoveryDeferredReqQueueProcessPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="ProcessPatientDiscoveryDeferredReqQueue">
            <soap:operation soapAction="urn:ProcessPatientDiscoveryDeferredReqQueue"/>
            <input name="ProcessPatientDiscoveryDeferredReqQueueRequest">
                <soap:body use="literal"/>
            </input>
            <output name="ProcessPatientDiscoveryDeferredReqQueueResponse">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>

    <service name="AdapterPatientDiscoveryDeferredReqQueueProcess">
        <port name="AdapterPatientDiscoveryDeferredReqQueueProcessPort" binding="tns:AdapterPatientDiscoveryDeferredReqQueueProcessBindingSoap">
            <soap:address location="http://localhost:${NhincHttpPort}/CONNECTAdapter/AdapterPatientDiscoveryDeferredReqQueueProcess"/>
        </port>
    </service>

    <plnk:partnerLinkType name="AdapterPatientDiscoveryDeferredReqQueueProcess">
        <!-- A partner link type is automatically generated when a new port 
             type is added. Partner link types are used by BPEL processes. 
             In a BPEL process, a partner link represents the interaction 
             between the BPEL process and a partner service. Each partner 
             link is associated with a partner link type.  A partner link 
             type characterizes the conversational relationship between two 
             services. The partner link type can have one or two roles.-->
        <plnk:role name="AdapterPatientDiscoveryDeferredReqQueueProcessPortTypeRole" portType="tns:AdapterPatientDiscoveryDeferredReqQueueProcessPortType"/>
    </plnk:partnerLinkType>
</definitions>
