<?xml version="1.0" encoding="UTF-8"?>
<!--
  Entity Document Retrieve Deferred Request
  -->
<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/"
   xmlns="http://schemas.xmlsoap.org/wsdl/"
   xmlns:tns="urn:gov:hhs:fha:nhinc:entitydocretrieve"
   xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   xmlns:ihe="urn:ihe:iti:xds-b:2007"
   xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
   xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
   xmlns:dr="http://www.hhs.gov/healthit/nhin"
   xmlns:wsoma="http://schemas.xmlsoap.org/ws/2004/09/policy/optimizedmimeserialization"
   xmlns:nccommondr="urn:gov:hhs:fha:nhinc:common:nhinccommonentity"
   name="EntityDocRetrieveDeferredRequest"
   targetNamespace="urn:gov:hhs:fha:nhinc:entitydocretrieve">
    <documentation>Entity document retrieve deferred request</documentation>
    <types>
        <xsd:schema>
            <xsd:import namespace="urn:ihe:iti:xds-b:2007"
                        schemaLocation="../schemas/ihe/XDS.b_DocumentRepository.xsd"/>
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:common:nhinccommonentity"
                        schemaLocation="../schemas/nhinc/common/NhincCommonEntity.xsd"/>
            <xsd:import namespace="http://www.hhs.gov/healthit/nhin"
                        schemaLocation="../schemas/nhin/RetrieveDocument.xsd"/>
        </xsd:schema>
    </types>
    <message name="CrossGatewayRetrieveRequestMessage">
        <part name="CrossGatewayRetrieveRequest"
              element="nccommondr:RespondingGateway_CrossGatewayRetrieveRequest"/>
    </message>
    <message name="CrossGatewayRetrieveAcknowledgementMessage">
        <part name="CrossGatewayRetrieveAcknowledgement"
              element="dr:DocRetrieveAcknowledgement"/>
    </message>

    <portType name="EntityDocRetrieveDeferredRequestPortType">
        <operation name="CrossGatewayRetrieveRequest">
            <input name="CrossGatewayRetrieveRequestMessage"
                   message="tns:CrossGatewayRetrieveRequestMessage" />
            <output name="CrossGatewayRetrieveAcknowledgement"
                    message="tns:CrossGatewayRetrieveAcknowledgementMessage"/>
        </operation>
    </portType>

    <binding name="EntityDocRetrieveDeferredRequestBindingSoap"
             type="tns:EntityDocRetrieveDeferredRequestPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsp:PolicyReference URI="#EntityDocRetrievePolicy"/>
        <operation name="CrossGatewayRetrieveRequest">
            <soap:operation soapAction="urn:CrossGatewayRetrieveRequest"/>
            <input name="CrossGatewayRetrieveRequestMessage">
                <soap:body use="literal"/>
            </input>
            <output name="CrossGatewayRetrieveAcknowledgement">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>

    <service name="EntityDocRetrieveDeferredRequest">
        <port name="EntityDocRetrieveDeferredRequestPortSoap"
          binding="tns:EntityDocRetrieveDeferredRequestBindingSoap">
            <soap:address
               location="http://localhost:${HttpDefaultPort}/NhinConnect/EntityDocRetrieveDeferredRequest"/>
        </port>
    </service>
    <wsp:Policy wsu:Id="EntityDocRetrievePolicy">
        <wsp:ExactlyOne>
            <wsp:All>
                <wsoma:OptimizedMimeSerialization/>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
</definitions>

