<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  Nhinc Proxy Document Retrieve
  -->
<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
   xmlns="http://schemas.xmlsoap.org/wsdl/" 
   xmlns:tns="urn:gov:hhs:fha:nhinc:nhincproxydocretrieve"
   xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
   xmlns:ihe="urn:ihe:iti:xds-b:2007" 
   xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" 
   xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" 
   xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" 
   xmlns:wsoma="http://schemas.xmlsoap.org/ws/2004/09/policy/optimizedmimeserialization" 
   xmlns:nccommonproxy="urn:gov:hhs:fha:nhinc:common:nhinccommonproxy"
   name="NhincProxyDocRetrieve" 
   targetNamespace="urn:gov:hhs:fha:nhinc:nhincproxydocretrieve">
    <documentation>Nhinc Proxy document retrieve</documentation>
    <types>
        <xsd:schema>
            <xsd:import namespace="urn:ihe:iti:xds-b:2007" 
                        schemaLocation="../schemas/ihe/XDS.b_DocumentRepository.xsd"/>
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:common:nhinccommonproxy"
                        schemaLocation="../schemas/nhinc/common/NhincCommonProxy.xsd"/>
        </xsd:schema>
    </types>
    <message name="RespondingGateway_CrossGatewayRetrieveRequestMessage">
        <part name="RespondingGateway_CrossGatewayRetrieveRequest" 
              element="nccommonproxy:RespondingGateway_CrossGatewayRetrieveRequest"/>
    </message>
    <message name="RespondingGateway_CrossGatewayRetrieveResponseMessage">
        <part name="RespondingGateway_CrossGatewayRetrieveResponse" 
              element="ihe:RetrieveDocumentSetResponse"/>
    </message>
    
    <portType name="NhincProxyDocRetrievePortType">
        <operation name="RespondingGateway_CrossGatewayRetrieve">
            <input name="RespondingGateway_CrossGatewayRetrieveRequest"
                   message="tns:RespondingGateway_CrossGatewayRetrieveRequestMessage" />
            <output name="RespondingGateway_CrossGatewayRetrieveResponse"
                    message="tns:RespondingGateway_CrossGatewayRetrieveResponseMessage"/>
        </operation>
    </portType>
    
    <binding name="NhincProxyDocRetrieveBindingSoap11" 
             type="tns:NhincProxyDocRetrievePortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsp:PolicyReference URI="#NhincProxyDocRetrievePolicy"/>
        <operation name="RespondingGateway_CrossGatewayRetrieve">
            <soap:operation soapAction="urn:RespondingGateway_CrossGatewayRetrieve"/>
            <input name="RespondingGateway_CrossGatewayRetrieveRequest">
                <soap:body use="literal"/>
            </input>
            <output name="RespondingGateway_CrossGatewayRetrieveResponse">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    
    <service name="NhincProxyDocRetrieve">
        <port name="NhincProxyDocRetrievePortSoap11" 
          binding="tns:NhincProxyDocRetrieveBindingSoap11">
            <soap:address 
               location="http://localhost:${HttpDefaultPort}/NhinConnect/NhincProxyDocRetrieve"/>
        </port>
    </service>
    
    <plnk:partnerLinkType name="NhincProxyDocRetrieve">
    <!-- A partner link type is automatically generated when a new port type is added. 
         Partner link types are used by BPEL processes. In a BPEL process, a partner 
         link represents the interaction between the BPEL process and a partner service. 
         Each partner link is associated with a partner link type. A partner link type 
         characterizes the conversational relationship between two services. The 
         partner link type can have one or two roles.-->
        <plnk:role name="NhincProxyDocRetrievePortTypeRole" 
               portType="tns:NhincProxyDocRetrievePortType"/>
    </plnk:partnerLinkType>
    
    <wsp:Policy wsu:Id="NhincProxyDocRetrievePolicy">
        <wsp:ExactlyOne>
            <wsp:All>
                <wsoma:OptimizedMimeSerialization/>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
</definitions>
