<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  Adapter Document Query Deferred Request Error WSDL
  -->
<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="urn:gov:hhs:fha:nhinc:adapterdocquerydeferredrequesterror" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:query="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsoma="http://schemas.xmlsoap.org/ws/2004/09/policy/optimizedmimeserialization" xmlns:nccommonadapter="urn:gov:hhs:fha:nhinc:common:nhinccommonadapter" xmlns:dq="http://www.hhs.gov/healthit/nhin" name="AdapterDocQueryDeferredRequestError" targetNamespace="urn:gov:hhs:fha:nhinc:adapterdocquerydeferredrequesterror">
	<documentation>Adapter Document Query Deferred Request Error</documentation>
	<types>
		<xsd:schema>
			<xsd:import namespace="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" schemaLocation="../schemas/ebRS/query.xsd"/>
			<xsd:import namespace="urn:gov:hhs:fha:nhinc:common:nhinccommonadapter" schemaLocation="../schemas/nhinc/common/NhincCommonAdapter.xsd"/>
			<xsd:import namespace="http://www.hhs.gov/healthit/nhin" schemaLocation="../schemas/nhin/QueryDocument.xsd"/>
		</xsd:schema>
	</types>
	<message name="RespondingGateway_CrossGatewayQueryRequestErrorMessage">
		<part name="RespondingGateway_CrossGatewayQueryRequest" element="nccommonadapter:AdapterDocumentQueryDeferredRequestError"/>
	</message>
	<message name="AcknowledgementMessage">
		<part name="RespondingGateway_CrossGatewayQueryResponse" element="dq:DocQueryAcknowledgement"/>
	</message>
	<portType name="AdapterDocQueryDeferredRequestErrorPortType">
		<operation name="RespondingGateway_CrossGatewayQuery">
			<input name="RespondingGateway_CrossGatewayQueryRequest" message="tns:RespondingGateway_CrossGatewayQueryRequestErrorMessage"/>
			<output name="AcknowledgementMessage" message="tns:AcknowledgementMessage"/>
		</operation>
	</portType>
	<binding name="AdapterDocQueryDeferredRequestErrorBindingSoap" type="tns:AdapterDocQueryDeferredRequestErrorPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="RespondingGateway_CrossGatewayQuery">
			<soap:operation soapAction="urn:RespondingGateway_CrossGatewayQuery"/>
			<input name="RespondingGateway_CrossGatewayQueryRequest">
				<soap:body use="literal"/>
			</input>
			<output name="AcknowledgementMessage">
				<soap:body use="literal"/>
			</output>
		</operation>
	</binding>
	<service name="AdapterDocQueryDeferredRequestError">
		<port name="AdapterDocQueryDeferredRequestErrorPortSoap" binding="tns:AdapterDocQueryDeferredRequestErrorBindingSoap">
			<soap:address location="http://localhost:${HttpDefaultPort}/NhinConnect/AdapterDocQueryDeferredRequest"/>
		</port>
	</service>
</definitions>
