<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" 
   xmlns:tns="urn:gov:hhs:fha:nhinc:nhincproxyauditlogquery"
   xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
   xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
   xmlns:iheaudit="http://nhinc.services.com/schema/auditmessage" 
   xmlns:nccommonproxy="urn:gov:hhs:fha:nhinc:common:nhinccommonproxy"
   xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" 
   xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
   name="NhincProxyAuditLogQuery" 
   targetNamespace="urn:gov:hhs:fha:nhinc:nhincproxyauditlogquery">

  <wsdl:types>
    <xsd:schema targetNamespace="http://services.nhin.com/wsdl/auditlogquery">
      <xsd:import namespace="http://nhinc.services.com/schema/auditmessage" 
                  schemaLocation="../schemas/ihe/auditmessage.xsd"/>
      <xsd:import namespace="urn:gov:hhs:fha:nhinc:common:nhinccommonproxy"
                  schemaLocation="../schemas/nhinc/common/NhincCommonProxy.xsd"/>
    </xsd:schema>
  </wsdl:types>

  <message name="findAuditEventsRequestMessage">
    <part name="FindAuditEventsRequest" element="nccommonproxy:FindAuditEventsRequest"/>
  </message>
  <message name="findAuditEventsResponseMessage">
    <part name="FindAuditEventsResponse" element="iheaudit:FindAuditEventsResponse"/>
  </message>

  <portType name="NhincProxyAuditLogQueryPortType">
    <operation name="findAuditEvents">
      <input name="findAuditEventsRequest" 
             message="tns:findAuditEventsRequestMessage"/>
      <output name="findAuditEventsResponse" 
              message="tns:findAuditEventsResponseMessage"/>
    </operation>
  </portType>

  <binding name="NhincProxyAuditLogQueryBindingSoap11" 
           type="tns:NhincProxyAuditLogQueryPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="findAuditEvents">
      <soap:operation soapAction="urn:findAuditEvents"/>
      <input name="findAuditEventsRequest">
        <soap:body use="literal"/>
      </input>
      <output name="findAuditEventsResponse">
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>

  <service name="NhincProxyAuditLogQuery">
    <port name="NhincProxyAuditLogQueryPortSoap11" 
          binding="tns:NhincProxyAuditLogQueryBindingSoap11">
      <soap:address 
         location="http://localhost:${NhincHttpPort}/NhinConnect/NhincProxyAuditLogQuery"/>
    </port>
  </service>

  <plnk:partnerLinkType name="NhincProxyAuditLogQuery">
    <!-- A partner link type is automatically generated when a new port type is added. 
             Partner link types are used by BPEL processes. In a BPEL process, a partner link 
             represents the interaction between the BPEL process and a partner service. Each 
             partner link is associated with a partner link type. A partner link type 
             characterizes the conversational relationship between two services. The partner link 
             type can have one or two roles.-->
    <plnk:role name="NhincProxyAuditLogQueryPortTypeRole" 
               portType="tns:NhincProxyAuditLogQueryPortType"/>
  </plnk:partnerLinkType>
</definitions>
