DROP TABLE IF EXISTS asyncmsgs.asyncmsgrepo;

CREATE TABLE IF NOT EXISTS asyncmsgs.asyncmsgrepo (
  Id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  MessageId VARCHAR(100) NOT NULL,
  CreationTime DATETIME NOT NULL,
  ResponseTime DATETIME NULL DEFAULT NULL,
  Duration BIGINT NULL DEFAULT 0,
  ServiceName VARCHAR(45) NULL DEFAULT NULL,
  Direction VARCHAR(10) NULL DEFAULT NULL,
  CommunityId VARCHAR(100) NULL DEFAULT NULL,
  Status VARCHAR(45) NULL DEFAULT NULL,
  ResponseType VARCHAR(10) NULL DEFAULT NULL,
  Reserved VARCHAR(100) NULL DEFAULT NULL,
  MsgData LONGBLOB NULL DEFAULT NULL,
  RspData LONGBLOB NULL DEFAULT NULL,
  AckData LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (Id)
);
