cp $GATEWAY_DIR/GatewayPolicyEngineTransformationEjb/dist/GatewayPolicyEngineTransformationEjb.jar ~/NHINC_Binaries/
cp $GATEWAY_DIR/AdapterDocQueryProxyEJB/dist/AdapterDocQueryProxyEJB.jar ~/NHINC_Binaries/
cp $GATEWAY_DIR/GatewaySubscriptionRepositoryEJB/dist/GatewaySubscriptionRepositoryEJB.jar ~/NHINC_Binaries/
cp $GATEWAY_DIR/AuditRepositoryEJB/dist/AuditRepositoryEJB.jar ~/NHINC_Binaries/
cp $GATEWAY_DIR/NhincSubjectDiscoveryEJB/dist/NhincSubjectDiscoveryEJB.jar ~/NHINC_Binaries/
cp $GATEWAY_DIR/EntityDocRetrieveEJB/dist/EntityDocRetrieveEJB.jar ~/NHINC_Binaries/
cp $GATEWAY_DIR/AdapterDocRetrieveProxyEJB/dist/AdapterDocRetrieveProxyEJB.jar ~/NHINC_Binaries/
cp $GATEWAY_DIR/AggregatorEJB/dist/AggregatorEJB.jar ~/NHINC_Binaries/
cp $GATEWAY_DIR/EntitySubjectDiscoveryEJB/dist/EntitySubjectDiscoveryEJB.jar ~/NHINC_Binaries/
cp $GATEWAY_DIR/PatientCorrelationFacadeDteEjb/dist/PatientCorrelationFacadeDteEjb.jar ~/NHINC_Binaries/
cp $GATEWAY_DIR/NhincDocRetrieveEJB/dist/NhincDocRetrieveEJB.jar ~/NHINC_Binaries/
cp $GATEWAY_DIR/AdapterSubjectDiscoveryProxyEJB/dist/AdapterSubjectDiscoveryProxyEJB.jar ~/NHINC_Binaries/
cp $GATEWAY_DIR/PatientCorrelationEJB/dist/PatientCorrelationEJB.jar ~/NHINC_Binaries/
cp $GATEWAY_DIR/NhincHiemSubscriptionEJB/dist/NhincHiemSubscriptionEJB.jar ~/NHINC_Binaries/
cp $GATEWAY_DIR/NhincDocQueryEJB/dist/NhincDocQueryEJB.jar ~/NHINC_Binaries/
cp $GATEWAY_DIR/NhincAuditQueryEJB/dist/NhincAuditQueryEJB.jar ~/NHINC_Binaries/
cp $GATEWAY_DIR/EntityHiemSubscriptionEJB/dist/EntityHiemSubscriptionEJB.jar ~/NHINC_Binaries/
cp $GATEWAY_DIR/HiemSubscriptionRepositoryUtilEJB/dist/HiemSubscriptionRepositoryUtilEJB.jar ~/NHINC_Binaries/
cp $GATEWAY_DIR/EntityDocQueryEJB/dist/EntityDocQueryEJB.jar ~/NHINC_Binaries/
cp $GATEWAY_DIR/AdapterPolicyEngineProxyEJB/dist/AdapterPolicyEngineProxyEJB.jar ~/NHINC_Binaries/
cp $GATEWAY_DIR/GatewayPolicyEngineFacadeEJB/dist/GatewayPolicyEngineFacadeEJB.jar ~/NHINC_Binaries/
cp $GATEWAY_DIR/EntityAuditLogQueryEJB/dist/EntityAuditLogQueryEJB.jar ~/NHINC_Binaries/

cp $ADAPTER_DIR/General/UniversalClientGUI/UniversalClientGUI.war  ~/NHINC_Binaries/

cp $ADAPTER_DIR/Mural/MuralMpiEJB/dist/MuralMpiEJB.jar ~/NHINC_Binaries/
cp $ADAPTER_DIR/GenericFileTransfer/FTATransferAdapterEJB/dist/FTATransferAdapterEJB.jar ~/NHINC_Binaries/
cp $ADAPTER_DIR/General/EntityDocRetrieveProxyEJB/dist/EntityDocRetrieveProxyEJB.jar ~/NHINC_Binaries/
cp $ADAPTER_DIR/General/DocumentRepositoryEJB/dist/DocumentRepositoryEJB.jar ~/NHINC_Binaries/
cp $ADAPTER_DIR/General/AdapterAuthenticationEJB/dist/AdapterAuthenticationEJB.jar ~/NHINC_Binaries/
cp $ADAPTER_DIR/General/AdapterPolicyEngineTransformEJB/dist/AdapterPolicyEngineTransformEJB.jar ~/NHINC_Binaries/
cp $ADAPTER_DIR/General/AdapterPEPEJB/dist/AdapterPEPEJB.jar ~/NHINC_Binaries/
cp $ADAPTER_DIR/General/AdapterMpiEJB/dist/AdapterMpiEJB.jar ~/NHINC_Binaries/
cp $ADAPTER_DIR/General/AdapterPolicyEngineOrchestratorEJB/dist/AdapterPolicyEngineOrchestratorEJB.jar ~/NHINC_Binaries/
cp $ADAPTER_DIR/General/EntitySubjectDiscoveryProxyEJB/dist/EntitySubjectDiscoveryProxyEJB.jar ~/NHINC_Binaries/
cp $ADAPTER_DIR/General/AdapterSubjectDiscoveryEJB/dist/AdapterSubjectDiscoveryEJB.jar ~/NHINC_Binaries/
cp $ADAPTER_DIR/General/AdapterMPIProxyEJB/dist/AdapterMPIProxyEJB.jar ~/NHINC_Binaries/
cp $ADAPTER_DIR/General/AdapterPIPEJB/dist/AdapterPIPEJB.jar ~/NHINC_Binaries/
cp $ADAPTER_DIR/General/EntityAuditQueryProxyEJB/dist/EntityAuditQueryProxyEJB.jar ~/NHINC_Binaries/
cp $ADAPTER_DIR/General/MpiEJB/dist/MpiEJB.jar ~/NHINC_Binaries/
cp $ADAPTER_DIR/General/AdapterDocRepository2Soap12EJB/dist/AdapterDocRepository2Soap12EJB.jar ~/NHINC_Binaries/
cp $ADAPTER_DIR/General/MpiManagerEJB/dist/MpiManagerEJB.jar ~/NHINC_Binaries/
cp $ADAPTER_DIR/General/AdapterReidentificationEJB/dist/AdapterReidentificationEJB.jar ~/NHINC_Binaries/
cp $ADAPTER_DIR/General/AdapterDocRegistryAndRepositoryEJB/dist/AdapterDocRegistryAndRepositoryEJB.jar ~/NHINC_Binaries/
cp $ADAPTER_DIR/General/AdapterPolicyEngineEJB/dist/AdapterPolicyEngineEJB.jar ~/NHINC_Binaries/
cp $ADAPTER_DIR/General/EntityDocQueryProxyEJB/dist/EntityDocQueryProxyEJB.jar ~/NHINC_Binaries/
cp $ADAPTER_DIR/General/AdapterAuditQueryEJB/dist/AdapterAuditQueryEJB.jar ~/NHINC_Binaries/

cp $COMMON_DIR/PropAccessorEJB/dist/PropAccessorEJB.jar ~/NHINC_Binaries/
cp $COMMON_DIR/UDDIUpdateManagerEJB/dist/UDDIUpdateManagerEJB.jar ~/NHINC_Binaries/
cp $COMMON_DIR/ConnectionManagerEJB/dist/ConnectionManagerEJB.jar ~/NHINC_Binaries/
cp $COMMON_DIR/DocumentTransformEJB/dist/DocumentTransformEJB.jar ~/NHINC_Binaries/

cp passfile ~/NHINC_Binaries/.
cp DeployAllBinaries.sh ~/NHINC_Binaries/.
chmod +x ~/NHINC_Binaries/DeployAllBinaries.sh
cp UndeployAllBinaries.sh ~/NHINC_Binaries/.
chmod +x ~/NHINC_Binaries/UndeployAllBinaries.sh

