<?xml version="1.0" encoding="utf-8"?>
<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:tns="urn:gov:hhs:fha:nhinc:adapterxdrrequest"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:ihe="urn:ihe:iti:xds-b:2007"
             xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
             xmlns:wsaws="http://www.w3.org/2006/05/addressing/wsdl"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:nccommonadapter="urn:gov:hhs:fha:nhinc:common:nhinccommonadapter"
             xmlns:xdr="http://www.hhs.gov/healthit/nhin"
             name="AdapterXDRRequest"
             targetNamespace="urn:gov:hhs:fha:nhinc:adapterxdrrequest">
    <documentation>IHE Adapter Component for XDR Request</documentation>
    <types>
        <xsd:schema>
            <xsd:import namespace="urn:ihe:iti:xds-b:2007" schemaLocation="../schemas/ihe/XDS.b_DocumentRepository.xsd"/>
            <xsd:import namespace="http://www.hhs.gov/healthit/nhin" schemaLocation="../schemas/nhin/xdr.xsd"/>
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:common:nhinccommonadapter" schemaLocation="../schemas/nhinc/common/NhincCommonAdapter.xsd"/>
        </xsd:schema>
    </types>
    <message name="XDRRequestInputMessage">
        <documentation>XDR Request Input Message</documentation>
        <part name="body" element="nccommonadapter:Adapter_ProvideAndRegisterDocumentSetRequest"/>
    </message>
    <message name="XDRRequestAcknowledgementMessage">
        <documentation>XDR Request Acknowledgement Message</documentation>
        <part name="body" element="xdr:XDRAcknowledgement"/>
    </message>
    <portType name="AdapterXDRRequest_PortType">
        <operation name="ProvideAndRegisterDocumentSet-bRequest">
            <input message="tns:XDRRequestInputMessage" 
                   wsaw:Action="urn:gov:hhs:fha:nhinc:adapterxdrrequest:XDRRequestInputMessage"/>
            <output message="tns:XDRRequestAcknowledgementMessage" 
                    wsaw:Action="urn:gov:hhs:fha:nhinc:adapterxdrrequest:XDRRequestAcknowledgementMessage"/>
        </operation>
    </portType>
    <binding name="AdapterXDRRequest_Binding" type="tns:AdapterXDRRequest_PortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <!-- <wsaws:UsingAddressing/> -->
        <operation name="ProvideAndRegisterDocumentSet-bRequest">
            <soap:operation soapAction="tns:ProvideAndRegisterDocumentSet-bRequest"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="AdapterXDRRequest_Service">
        <port name="AdapterXDRRequest_Port" binding="tns:AdapterXDRRequest_Binding">
            <soap:address location="https://localhost:${HttpsDefaultPort}/AdapterXDRRequest"/>
        </port>
    </service>
</definitions>
