insert into docassembly.das_config values('das.ahlta.user', 'DAS', 'Y');
insert into docassembly.das_config values('das.calservice.endpoint', 'http://localhost:8080/CommonDataLayerServiceDODService/ICDBCALService?wsdl', 'Y');
insert into docassembly.das_config values('das.demo', 'on', 'Y');
insert into docassembly.das_config values('das.demo.data.directory', '/NHIN/demo-files', 'Y');
insert into docassembly.das_config values('das.demo.doc.date', '', 'Y');
insert into docassembly.das_config values('das.demo.patient', '', 'Y');
insert into docassembly.das_config values('das.persistenceUnit', 'DocumentAssemblerServicePU', 'Y');
insert into docassembly.das_config values('das.terminologyservice.endpoint', 'http://localhost:8080/TerminologyService/TerminologyService?wsdl', 'Y');
insert into docassembly.das_config values('das.test', 'off', 'Y');
insert into docassembly.das_config values('das.version', '1.0', 'Y');
insert into docassembly.das_config values('DEF_CONFIDENTIAL_CODE', 'N', 'Y');
insert into docassembly.das_config values('DEF_CONFIDENTIAL_CODE_DESCR', 'Normal', 'Y');
insert into docassembly.das_config values('DEF_CONFIDENTIAL_CODE_SYS_OID', '2.16.840.1.113883.5.25', 'Y');
insert into docassembly.das_config values('DEF_FORMAT_CODE_DESCR', 'HL7 CCD Document', 'Y');
insert into docassembly.das_config values('DEF_FORMAT_CODE_OID', '2.16.840.1.1.113883.10.20.1', 'Y');
insert into docassembly.das_config values('DEF_LANGUAGE', 'EN-US', 'Y');
insert into docassembly.das_config values('HCFT_CODE', '2865M2000N', 'Y');
insert into docassembly.das_config values('HCFT_CODE_DESCR', 'Hospitals; Military; Medical Center', 'Y');
insert into docassembly.das_config values('HCFT_CODE_SYS_OID', '2.16.840.1.1.113883.5.111', 'Y');
insert into docassembly.das_config values('HL7_DELIMITER', '^', 'Y');
insert into docassembly.das_config values('ORGANIZATION_NAME', 'Department of Defense', 'Y');
insert into docassembly.das_config values('ORGANIZATION_OID', '2.16.840.1.113883.3.198', 'Y');
insert into docassembly.das_config values('ORGANIZATION_SYS', 'AHLTA', 'Y');
insert into docassembly.das_config values('ORGANIZATION_SYS_TYPE', 'Automated System', 'Y');
insert into docassembly.das_config values('PRACTICE_SETTING_CODE', '410001006', 'Y');
insert into docassembly.das_config values('PRACTICE_SETTING_CODE_DESCR', 'Military Medicine', 'Y');
insert into docassembly.das_config values('PRACTICE_SETTING_CODE_SYS_NAME', 'SNOMED-CT', 'Y');
insert into docassembly.das_config values('PRACTICE_SETTING_CODE_SYS_OID', '2.16.840.1.113883.6.96', 'Y');
insert into docassembly.das_config values('RXNORM_CODE_SYS_NAME', 'RXNorm', 'Y');
insert into docassembly.das_config values('RXNORM_CODE_SYS_OID', '2.16.840.1.113883.6.88', 'Y');
insert into docassembly.das_config values('SNOMED_CODE_SYS_NAME', 'SNOMED-CT', 'Y');
insert into docassembly.das_config values('SNOMED_CODE_SYS_OID', '2.16.840.1.113883.6.96', 'Y');
commit;