package gov.hhs.fha.nhinc.logger;

public enum TransactionType {

	PD_GATEWAY_TRANSACTION,
	QD_GATEWAY_TRANSACTION,
	RD_GATEWAY_TRANSACTION,
	PD_ADAPTER_TRANSACTION,
	QD_ADAPTER_TRANSACTION,
	RD_ADAPTER_TRANSACTION;
	
}
