package gov.hhs.fha.nhinc.logger;

public enum TransactionType {

	PD_GATEWAY_TRANSACTION,
	QD_GATEWAY_TRANSACTION,
	RD_GATEWAY_TRANSACTION,
	PD_INTERNAL_TRANSACTION,
	QD_INTERNAL_TRANSACTION,
	RD_INTERNAL_TRANSACTION;
	
}
