<?xml version='1.0' encoding='UTF-8'?><!-- Published by JAX-WS RI at http://jax-ws.dev.java.net. RI's version is JAX-WS RI 2.1.6-hudson-317-. --><definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="urn:gov:hhs:fha:nhinc:testpepservice" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:pep="urn:gov:hhs:fha:nhinc:testpepschema" name="TestPEPService" targetNamespace="urn:gov:hhs:fha:nhinc:testpepservice">
    <types>
        <xsd:schema>
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:testpepschema" schemaLocation="http://localhost:8080/TestPEP/TestPEPServiceService?xsd=1" />
        </xsd:schema>
    </types>
    <message name="EnforceResourceRequestMessage">
        <part name="EnforceResourceInput" element="pep:EnforceResourceInput" />
    </message>
    <message name="EnforceResourceResponseMessage">
        <part name="EnforceResourceOutput" element="pep:EnforceResourceOutput" />
    </message>
    <portType name="TestPEPServicePortType">
        <operation name="EnforceResource">
            <input name="EnforceResourceRequest" message="tns:EnforceResourceRequestMessage" />
            <output name="EnforceResourceResponse" message="tns:EnforceResourceResponseMessage" />
        </operation>
    </portType>
    <binding name="TestPEPServiceBinding" type="tns:TestPEPServicePortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
        <operation name="EnforceResource">
            <soap:operation soapAction="urn:EnforceResource" />
            <input name="EnforceResourceRequest">
                <soap:body use="literal" />
            </input>
            <output name="EnforceResourceResponse">
                <soap:body use="literal" />
            </output>
        </operation>
    </binding>
    <service name="TestPEPServiceService">
        <port name="TestPEPServicePort" binding="tns:TestPEPServiceBinding">
            <soap:address location="http://localhost:8080/TestPEP/TestPEPServiceService" />
        </port>
    </service>
    <plnk:partnerLinkType name="TestPEPService">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="TestPEPServicePortTypeRole" portType="tns:TestPEPServicePortType" />
    </plnk:partnerLinkType>
</definitions>