<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:tns="urn:gov:hhs:fha:nhinc:adapterpatientdiscoverysecured"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/"
                  xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xmlns:hl7="urn:hl7-org:v3"
                  xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                  xmlns:nccommonadapter="urn:gov:hhs:fha:nhinc:common:nhinccommonadapter"
                  xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
                  xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
                  xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
                  xmlns:wsaws="http://www.w3.org/2005/08/addressing"
                  xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702"
                  xmlns:sc="http://schemas.sun.com/2006/03/wss/server"
                  xmlns:wspp="http://java.sun.com/xml/ns/wsit/policy"
                  xmlns:nhin="http://www.hhs.gov/healthit/nhin"
                  name="AdapterPatientDiscoverySecured"
                  targetNamespace="urn:gov:hhs:fha:nhinc:adapterpatientdiscoverysecured">
    <wsdl:documentation>
     WSDL for Adapter interface of Patient Discovery
    </wsdl:documentation>
    <wsdl:types>
        <xsd:schema elementFormDefault="qualified" targetNamespace="urn:hl7-org:v3" xmlns:hl7="urn:hl7-org:v3">
            <xsd:include schemaLocation="../schemas/nhinc/hl7/RespondingGateway_PRPA_IN201305UV02Request.xsd"/>
            <xsd:include schemaLocation="../schemas/HL7V3/NE2008/multicacheschemas/PRPA_IN201306UV02.xsd"/>
        </xsd:schema>
        <xsd:schema targetNamespace="urn:gov:hhs:fha:nhinc:adapterpatientdiscoverysecured">
            <xsd:import schemaLocation="../schemas/nhin/PatientDiscoveryFault.xsd" namespace="http://www.hhs.gov/healthit/nhin"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="RespondingGateway_PRPA_IN201305UV02RequestSecuredMessage">
        <wsdl:part name="RespondingGateway_PRPA_IN201305UV02Request" element="hl7:RespondingGateway_PRPA_IN201305UV02Request"/>
    </wsdl:message>
    <wsdl:message name="RespondingGateway_PRPA_IN201306UV02ResponseSecuredMessage">
        <wsdl:part name="RespondingGateway_PRPA_IN201306UV02Response" element="hl7:PRPA_IN201306UV02"/>
    </wsdl:message>
    <wsdl:message name="AdapterPatientDiscoverySecuredFault">
        <wsdl:part name="PatientDiscoveryFault" element="nhin:PatientDiscoveryFault"/>
    </wsdl:message>
    <wsdl:portType name="AdapterPatientDiscoverySecuredPortType">
        <wsdl:operation name="RespondingGateway_PRPA_IN201305UV02">
            <wsdl:input name="RespondingGateway_PRPA_IN201305UV02RequestSecured" message="tns:RespondingGateway_PRPA_IN201305UV02RequestSecuredMessage"/>
            <wsdl:output name="RespondingGateway_PRPA_IN201306UV02ResponseSecured" message="tns:RespondingGateway_PRPA_IN201306UV02ResponseSecuredMessage"/>
            <wsdl:fault name="AdapterPatientDiscoverySecuredFault" message="tns:AdapterPatientDiscoverySecuredFault"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="AdapterPatientDiscoverySecuredBindingSoap" type="tns:AdapterPatientDiscoverySecuredPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsp:PolicyReference URI="#Adapter_PatientDiscovery_SoapPolicy"/>
        <wsdl:operation name="RespondingGateway_PRPA_IN201305UV02">
            <soap:operation soapAction="urn:RespondingGateway_PRPA_IN201305UV02"/>
            <wsdl:input name="RespondingGateway_PRPA_IN201305UV02RequestSecured">
                <soap:body use="literal"/>
                <wsp:PolicyReference URI="#Adapter_PatientDiscovery_Input_Policy"/>
            </wsdl:input>
            <wsdl:output name="RespondingGateway_PRPA_IN201306UV02ResponseSecured">
                <soap:body use="literal"/>
                <wsp:PolicyReference URI="#Adapter_PatientDiscovery_Output_Policy"/>
            </wsdl:output>
            <wsdl:fault name="AdapterPatientDiscoverySecuredFault">
                <soap:fault name="AdapterPatientDiscoverySecuredFault" use="literal"/>
                <wsp:PolicyReference URI="#Adapter_PatientDiscovery_Output_Policy"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="AdapterPatientDiscoverySecured">
        <wsdl:port name="AdapterPatientDiscoverySecuredPortSoap" binding="tns:AdapterPatientDiscoverySecuredBindingSoap">
            <soap:address location="https://localhost:${HttpsDefaultPort}/Adapter/PatientDiscovery/A_0/AdapterPatientDiscoverySecured"/>
        </wsdl:port>
    </wsdl:service>
    <wsp:Policy wsu:Id="Adapter_PatientDiscovery_SoapPolicy">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:TransportBinding>
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken>
                                    <wsp:Policy>
                                        <sp:RequireClientCertificate/>
                                    </wsp:Policy>
                                </sp:HttpsToken>
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Strict/>
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp/>
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic256/>
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                    </wsp:Policy>
                </sp:TransportBinding>
                <sp:EndorsingSupportingTokens>
                    <wsp:Policy>
                        <sp:SamlToken sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                            <wsp:Policy>
                                <sp:WssSamlV20Token11/>
                            </wsp:Policy>
                        </sp:SamlToken>
                    </wsp:Policy>
                </sp:EndorsingSupportingTokens>
                <sp:Wss11>
                    <wsp:Policy>
                        <sp:MustSupportRefKeyIdentifier/>
                        <sp:MustSupportRefIssuerSerial/>
                        <sp:RequireSignatureConfirmation/>
                    </wsp:Policy>
                </sp:Wss11>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    <wsp:Policy wsu:Id="Adapter_PatientDiscovery_Input_Policy">
        <wsp:ExactlyOne>
            <wsp:All>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    <wsp:Policy wsu:Id="Adapter_PatientDiscovery_Output_Policy">
        <wsp:ExactlyOne>
            <wsp:All>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    <plnk:partnerLinkType name="AdapterPatientDiscoverySecured">
        <!-- A partner link type is automatically generated when a new port type is added.
         Partner link types are used by BPEL processes. In a BPEL process, a partner
         link represents the interaction between the BPEL process and a partner service.
         Each partner link is associated with a partner link type. A partner link type
         characterizes the conversational relationship between two services. The
         partner link type can have one or two roles.-->
        <plnk:role name="AdapterPatientDiscoverySecuredPortTypeRole" portType="tns:AdapterPatientDiscoverySecuredPortType"/>
    </plnk:partnerLinkType>
</wsdl:definitions>
