<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:tns="urn:gov:hhs:fha:nhinc:adapterpatientdiscoveryasyncresp" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:hl7="urn:hl7-org:v3" xmlns:wsaws="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:nccommonadapter="urn:gov:hhs:fha:nhinc:common:nhinccommonadapter" name="AdapterPatientDiscoveryAsyncResp" targetNamespace="urn:gov:hhs:fha:nhinc:adapterpatientdiscoveryasyncresp">
	<wsdl:documentation>
     WSDL for Adapter Interface for Patient Discovery Asynchronous Responses
    </wsdl:documentation>
	<wsdl:types>
		<xsd:schema elementFormDefault="qualified" targetNamespace="urn:hl7-org:v3" xmlns:hl7="urn:hl7-org:v3">
			<xsd:include schemaLocation="../schemas/nhinc/hl7/RespondingGateway_PRPA_IN201306UV02Request.xsd"/>
			<xsd:include schemaLocation="../schemas/HL7V3/NE2008/multicacheschemas/MCCI_IN000002UV01.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="ProcessPatientDiscoveryAsyncRespRequestMessage">
		<wsdl:part name="ProcessPatientDiscoveryAsyncRespAsyncRequest" element="hl7:RespondingGateway_PRPA_IN201306UV02Request"/>
	</wsdl:message>
	<wsdl:message name="ProcessPatientDiscoveryAsyncRespResponseMessage">
		<wsdl:part name="ProcessPatientDiscoveryAsyncRespAsyncResponse" element="hl7:MCCI_IN000002UV01"/>
	</wsdl:message>
	<wsdl:portType name="AdapterPatientDiscoveryAsyncRespPortType">
		<wsdl:operation name="ProcessPatientDiscoveryAsyncResp">
			<wsdl:input name="ProcessPatientDiscoveryAsyncRespAsyncRequest" message="tns:ProcessPatientDiscoveryAsyncRespRequestMessage" wsaw:Action="urn:gov:hhs:fha:nhinc:adapterpatientdiscoveryasyncresp:ProcessPatientDiscoveryAsyncRespAsyncRequest"/>
			<wsdl:output name="ProcessPatientDiscoveryAsyncRespAsyncResponse" message="tns:ProcessPatientDiscoveryAsyncRespResponseMessage" wsaw:Action="urn:gov:hhs:fha:nhinc:adapterpatientdiscoveryasyncresp:ProcessPatientDiscoveryAsyncRespAsyncResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="AdapterPatientDiscoveryAsyncRespBindingSoap" type="tns:AdapterPatientDiscoveryAsyncRespPortType">
		<soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="ProcessPatientDiscoveryAsyncResp">
			<wsdl:input name="ProcessPatientDiscoveryAsyncRespAsyncRequest">
				<soap12:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="ProcessPatientDiscoveryAsyncRespAsyncResponse">
				<soap12:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="AdapterPatientDiscoveryAsyncResp">
		<wsdl:port name="AdapterPatientDiscoveryAsyncRespPortSoap" binding="tns:AdapterPatientDiscoveryAsyncRespBindingSoap">
			<soap12:address location="http://localhost:${DefaultHTTPPort}/Adapter/PatientDiscovery/A_0/AdapterPatientDiscoveryDeferredResponseUnsecured"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
