<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:tns="urn:gov:hhs:fha:nhinc:entitypatientdiscovery"
   xmlns:wsoap11="http://schemas.xmlsoap.org/wsdl/soap/" 
   xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
   xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
   xmlns:hl7="urn:hl7-org:v3"
   xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" 
   name="EntityPatientDiscovery"
   targetNamespace="urn:gov:hhs:fha:nhinc:entitypatientdiscovery">
    <wsdl:documentation>
     WSDL for Entity interface of Patient Discovery
    </wsdl:documentation>
    <wsdl:types>
        <xsd:schema elementFormDefault="qualified"
                targetNamespace="urn:hl7-org:v3" xmlns:hl7="urn:hl7-org:v3">
      <!-- Include the message schema -->
            <xsd:include schemaLocation="../schemas/nhinc/hl7/HL7PatientDiscoveryMessages.xsd"/>
        </xsd:schema>  
    </wsdl:types>
    
    <wsdl:message name="RespondingGateway_PRPA_IN201305UV02RequestMessage">
        <wsdl:part name="RespondingGateway_PRPA_IN201305UV02Request"
               element="hl7:RespondingGateway_PRPA_IN201305UV02Request"/>
    </wsdl:message>
    <wsdl:message name="RespondingGateway_PRPA_IN201306UV02ResponseMessage">
        <wsdl:part name="RespondingGateway_PRPA_IN201306UV02Response"
               element="hl7:RespondingGateway_PRPA_IN201306UV02Response"/>
    </wsdl:message>

    <wsdl:portType name="EntityPatientDiscoveryPortType">
        <wsdl:operation name="RespondingGateway_PRPA_IN201305UV02">
            <wsdl:input name="RespondingGateway_PRPA_IN201305UV02Request"
                  message="tns:RespondingGateway_PRPA_IN201305UV02RequestMessage"/>
            <wsdl:output name="RespondingGateway_PRPA_IN201306UV02Response"
                   message="tns:RespondingGateway_PRPA_IN201306UV02ResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="EntityPatientDiscoveryBindingSoap11"
                type="tns:EntityPatientDiscoveryPortType">
        <wsoap11:binding style="document"
                     transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="RespondingGateway_PRPA_IN201305UV02">
            <wsoap11:operation soapAction="urn:RespondingGateway_PRPA_IN201305UV02"/>
            <wsdl:input name="RespondingGateway_PRPA_IN201305UV02Request" >
                <wsoap11:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="RespondingGateway_PRPA_IN201306UV02Response" >
                <wsoap11:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="EntityPatientDiscovery">
        <wsdl:port name="EntityPatientDiscoveryPortSoap11"
               binding="tns:EntityPatientDiscoveryBindingSoap11">
            <wsoap11:address
          location="https://localhost:${HttpsDefaultPort}/NhinConnect/EntityPatientDiscovery"/>
        </wsdl:port>
    </wsdl:service>

      <plnk:partnerLinkType name="EntityPatientDiscovery">
    <!-- A partner link type is automatically generated when a new port type is added. 
         Partner link types are used by BPEL processes. In a BPEL process, a partner 
         link represents the interaction between the BPEL process and a partner service. 
         Each partner link is associated with a partner link type. A partner link type 
         characterizes the conversational relationship between two services. The 
         partner link type can have one or two roles.-->
        <plnk:role name="EntityPatientDiscoveryPortTypeRole"
               portType="tns:EntityPatientDiscoveryPortType"/>
    </plnk:partnerLinkType>
  
</wsdl:definitions>
