<?xml version="1.0" encoding="UTF-8"?>
<definitions name="EntityComponentInternalSubscribeOrch" targetNamespace="urn:gov:hhs:fha:nhinc:entitycomponentinternalsubscribeorch"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:tns="urn:gov:hhs:fha:nhinc:entitycomponentinternalsubscribeorch" 
    xmlns:nccommonentity="urn:gov:hhs:fha:nhinc:common:nhinccommonentity" 
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <types>
        <xsd:schema targetNamespace="urn:gov:hhs:fha:nhinc:entitycomponentinternalsubscribeorch">
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:common:nhinccommonentity" schemaLocation="../schemas/nhinc/common/NhincCommonEntity.xsd"/>
        </xsd:schema>
    </types>
    <message name="SubscribeDocumentRequestMessage">
        <part name="SubscribeDocumentRequest" element="nccommonentity:SubscribeDocumentRequest"/>
    </message>
    <message name="SubscribeDocumentResponseMessage">
        <part name="SubscribeDocumentResponse" element="nccommonentity:SubscribeDocumentResponse"/>
    </message>
    <portType name="EntityComponentInternalSubscribeOrchPortType">
        <operation name="SubscribeDocument">
            <input name="SubscribeDocumentRequest" message="tns:SubscribeDocumentRequestMessage"/>
            <output name="SubscribeDocumentResponse" message="tns:SubscribeDocumentResponseMessage"/>
        </operation>
    </portType>
    <binding name="EntityComponentInternalSubscribeOrchPortTypeBinding" type="tns:EntityComponentInternalSubscribeOrchPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="SubscribeDocument">
            <soap:operation soapAction="urn:SubscribeDocument"/>
            <input name="SubscribeDocumentRequest">
                <soap:body use="literal"/>
            </input>
            <output name="SubscribeDocumentResponse">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="EntityComponentInternalSubscribeOrchService">
        <port name="EntityComponentInternalSubscribeOrchPortTypeBindingPort" binding="tns:EntityComponentInternalSubscribeOrchPortTypeBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/NhinConnect/EntityComponentInternalSubscribeOrch"/>
        </port>
    </service>
    <plnk:partnerLinkType name="EntityComponentInternalSubscribeOrch">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="EntityComponentInternalSubscribeOrchPortTypeRole" portType="tns:EntityComponentInternalSubscribeOrchPortType"/>
    </plnk:partnerLinkType>
</definitions>
