<?xml version="1.0" encoding="UTF-8"?>
<definitions name="EntityComponentInternalDocQueryOrch" targetNamespace="urn:gov:hhs:fha:nhinc:entitycomponentinternaldocqueryorch"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:tns="urn:gov:hhs:fha:nhinc:entitycomponentinternaldocqueryorch" 
    xmlns:entintorch="urn:gov:hhs:fha:nhinc:common:entitycommoninternalorch" 
    xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema targetNamespace="urn:gov:hhs:fha:nhinc:entitycomponentinternaldocqueryorch">
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:common:entitycommoninternalorch" schemaLocation="../schemas/nhinc/common/EntityCommonInternalOrch.xsd"/>
        </xsd:schema>
    </types>
    <message name="SendAdhocQueryRequestMessage">
        <part name="SendAdhocQueryRequest" element="entintorch:SendAdhocQueryRequest"/>
    </message>
  <message name="SendAdhocQueryResponseMessage">
    <part name="SendAdhocQueryResponse" element="entintorch:SendAdhocQueryResponse"/>
  </message>
    <portType name="EntityComponentInternalDocQueryOrchPortType">
        <operation name="SendAdhocQuery">
            <input name="SendAdhocQueryRequest" message="tns:SendAdhocQueryRequestMessage"/>
            <output name="SendAdhocQueryResponse" message="tns:SendAdhocQueryResponseMessage"/>
        </operation>
    </portType>
    <binding name="EntityComponentInternalDocQueryOrchPortTypeBinding" type="tns:EntityComponentInternalDocQueryOrchPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="SendAdhocQuery">
            <soap:operation soapAction="urn:SendAdhocQuery"/>
            <input name="SendAdhocQueryRequest">
                <soap:body use="literal"/>
            </input>
            <output name="SendAdhocQueryResponse">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="EntityComponentInternalDocQueryOrchService">
        <port name="EntityComponentInternalDocQueryOrchPortTypeBindingPort" binding="tns:EntityComponentInternalDocQueryOrchPortTypeBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/NhinConnect/EntityComponentInternalDocQueryOrch"/>
        </port>
    </service>
    <plnk:partnerLinkType name="EntityComponentInternalDocQueryOrch">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="EntityComponentInternalDocQueryOrchPortTypeRole" portType="tns:EntityComponentInternalDocQueryOrchPortType"/>
    </plnk:partnerLinkType>
</definitions>
