<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:tns="urn:gov:hhs:fha:nhinc:entitypatientdiscoveryasyncreq"
   xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
   xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
   xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xmlns:hl7="urn:hl7-org:v3"
   xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
   xmlns:wsaws="http://www.w3.org/2006/05/addressing/wsdl"
   name="EntityPatientDiscoveryAsyncReq"
   targetNamespace="urn:gov:hhs:fha:nhinc:entitypatientdiscoveryasyncreq">
    <wsdl:documentation>
     WSDL for Entity interface of Patient Discovery Asynchronous Requests
    </wsdl:documentation>
    <wsdl:types>
        <xsd:schema elementFormDefault="qualified"
                targetNamespace="urn:hl7-org:v3" xmlns:hl7="urn:hl7-org:v3">
      <!-- Include the message schema -->
            <xsd:include schemaLocation="../schemas/nhinc/hl7/RespondingGateway_PRPA_IN201305UV02Request.xsd"/>
            <xsd:include schemaLocation="../schemas/HL7V3/NE2008/multicacheschemas/MCCI_IN000002UV01.xsd"/>
        </xsd:schema>
    </wsdl:types>
    
    <wsdl:message name="ProcessPatientDiscoveryAsyncReqRequestMessage">
        <wsdl:part name="ProcessPatientDiscoveryAsyncReqAsyncRequest"
               element="hl7:RespondingGateway_PRPA_IN201305UV02Request"/>
    </wsdl:message>
    <wsdl:message name="ProcessPatientDiscoveryAsyncReqResponseMessage">
        <wsdl:part name="ProcessPatientDiscoveryAsyncReqAsyncResponse"
               element="hl7:MCCI_IN000002UV01"/>
    </wsdl:message>

    <wsdl:portType name="EntityPatientDiscoveryAsyncReqPortType">
        <wsdl:operation name="ProcessPatientDiscoveryAsyncReq">
            <wsdl:input name="ProcessPatientDiscoveryAsyncReqAsyncRequest"
                  message="tns:ProcessPatientDiscoveryAsyncReqRequestMessage"
                  wsaw:Action="urn:gov:hhs:fha:nhinc:entitypatientdiscoveryasyncreq:ProcessPatientDiscoveryAsyncReqAsyncRequest"/>
            <wsdl:output name="ProcessPatientDiscoveryAsyncReqAsyncResponse"
                   message="tns:ProcessPatientDiscoveryAsyncReqResponseMessage"
                   wsaw:Action="urn:gov:hhs:fha:nhinc:entitypatientdiscoveryasyncreq:ProcessPatientDiscoveryAsyncReqAsyncResponse"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="EntityPatientDiscoveryAsyncReqBindingSoap"
                type="tns:EntityPatientDiscoveryAsyncReqPortType">
        <soap12:binding style="document"
                     transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsaws:UsingAddressing/>
        <wsdl:operation name="ProcessPatientDiscoveryAsyncReq">
            <wsdl:input name="ProcessPatientDiscoveryAsyncReqAsyncRequest" >
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="ProcessPatientDiscoveryAsyncReqAsyncResponse" >
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="EntityPatientDiscoveryAsyncReq">
        <wsdl:port name="EntityPatientDiscoveryAsyncReqPortSoap"
               binding="tns:EntityPatientDiscoveryAsyncReqBindingSoap">
            <soap12:address location="http://localhost:${HttpDefaultPort}/Gateway/PatientDiscovery/1_0/EntityService/EntityPatientDiscoveryDeferredRequestUnsecured"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>


