<?xml version="1.0" encoding="UTF-8"?>
<definitions name="EntityXDRSecured"
    targetNamespace="urn:gov:hhs:fha:nhinc:entityxdrsecured"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2"
    xmlns:ihe="urn:ihe:iti:xds-b:2007"
    xmlns:hl7="urn:hl7-org:v3"
    xmlns:rs="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0"
    xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
    xmlns:wsaws="http://www.w3.org/2005/08/addressing"
    xmlns:wsrf-rw="http://docs.oasis-open.org/wsrf/rw-2"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsoma="http://schemas.xmlsoap.org/ws/2004/09/policy/optimizedmimeserialization"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:tns="urn:gov:hhs:fha:nhinc:entityxdrsecured"
    xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
    xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
    xmlns:wspp="http://java.sun.com/xml/ns/wsit/policy"
    xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
    xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy"
    xmlns:sc="http://schemas.sun.com/2006/03/wss/server"
    xmlns:ns6="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0"   
    xmlns:nccommonentity="urn:gov:hhs:fha:nhinc:common:nhinccommonentity"
    >
    <types>
        <xsd:schema>
            <xsd:import namespace="urn:ihe:iti:xds-b:2007"
                        schemaLocation="../schemas/ihe/XDS.b_DocumentRepository.xsd"/>
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:gateway:samltokendata"
                        schemaLocation="../schemas/nhinc/gateway/SamlTokenData.xsd"/>
            <xsd:import schemaLocation="../schemas/ebRS/rs.xsd"
                        namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0"/>
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:common:nhinccommonentity"
                        schemaLocation="../schemas/nhinc/common/NhincCommonEntity.xsd"/>
        </xsd:schema>
    </types>
    <message name="RespondingGateway_ProvideAndRegisterDocumentSet-bRequest_Message">
        <part name="body" type="nccommonentity:RespondingGateway_ProvideAndRegisterDocumentSetSecuredRequestType"/>
    </message>
    <message name="RespondingGateway_ProvideAndRegisterDocumentSet-bResponse_Message">
        <part name="body" type="rs:RegistryResponseType"/>
    </message>
    <portType name="EntityXDRSecuredPortType">
        <operation name="RespondingGateway_ProvideAndRegisterDocumentSet-b">
            <input name="input1" message="tns:RespondingGateway_ProvideAndRegisterDocumentSet-bRequest_Message"/>
            <output name="output1" message="tns:RespondingGateway_ProvideAndRegisterDocumentSet-bResponse_Message"/>
        </operation>
    </portType>
    <binding name="EntityXDRSecuredBindingSoap11"
             type="tns:EntityXDRSecuredPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsp:PolicyReference URI="#RespondingGateway_XDR_Binding_SoapPolicy"/>
        <operation name="RespondingGateway_ProvideAndRegisterDocumentSet-b">
            <soap:operation soapAction="urn:RespondingGateway_ProvideAndRegisterDocumentSet"/>
            <input name="input1">
                <soap:body use="literal"/>
                <wsp:PolicyReference URI="#RespondingGateway_XDR_Binding_Soap_Input_Policy"/>
            </input>
            <output name="output1">
                <soap:body use="literal"/>
                <wsp:PolicyReference URI="#RespondingGateway_XDR_Binding_Soap_Output_Policy"/>
            </output>
        </operation>
    </binding>

    <service name="EntityXDRSecured">
        <port name="EntityXDRPortSoap11"
          binding="tns:EntityXDRSecuredBindingSoap11">
            <soap:address
               location="https://localhost:${HttpsDefaultPort}/NhinConnect/EntityXDRSecured"/>
        </port>
    </service>
  <wsp:Policy wsu:Id="RespondingGateway_XDR_Binding_SoapPolicy">
    <wsp:ExactlyOne>
      <wsp:All>
        <wsoma:OptimizedMimeSerialization/>
        <wsaws:UsingAddressing xmlns:wsaws="http://www.w3.org/2006/05/addressing/wsdl"/>
        <sc:KeyStore wspp:visibility="private"
                     aliasSelector="gov.hhs.fha.nhinc.callback.KeyStoreServerAliasSelector"
                     callbackHandler="gov.hhs.fha.nhinc.callback.KeyStoreCallbackHandler"/>
        <sc:TrustStore wspp:visibility="private"
                       callbackHandler="gov.hhs.fha.nhinc.callback.TrustStoreCallbackHandler"/>
        <sp:TransportBinding>
          <wsp:Policy>
            <sp:TransportToken>
              <wsp:Policy>
                <sp:HttpsToken>
                  <wsp:Policy>
                    <sp:RequireClientCertificate/>
                  </wsp:Policy>
                </sp:HttpsToken>
              </wsp:Policy>
            </sp:TransportToken>
            <sp:Layout>
              <wsp:Policy>
                <sp:Strict/>
              </wsp:Policy>
            </sp:Layout>
            <sp:IncludeTimestamp/>
            <sp:AlgorithmSuite>
              <wsp:Policy>
                <sp:Basic128/>
              </wsp:Policy>
            </sp:AlgorithmSuite>
          </wsp:Policy>
        </sp:TransportBinding>
        <sp:EndorsingSupportingTokens>
          <wsp:Policy>
            <sp:SamlToken
                sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
              <wsp:Policy>
                <sp:WssSamlV20Token11/>
              </wsp:Policy>
            </sp:SamlToken>
          </wsp:Policy>
        </sp:EndorsingSupportingTokens>
        <sp:Wss11>
          <wsp:Policy>
            <sp:MustSupportRefKeyIdentifier/>
            <sp:MustSupportRefIssuerSerial/>
            <sp:RequireSignatureConfirmation/>
          </wsp:Policy>
        </sp:Wss11>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>

    <wsp:Policy wsu:Id="RespondingGateway_XDR_Binding_Soap_Input_Policy">
        <wsp:ExactlyOne>
            <wsp:All>
                <wsoma:OptimizedMimeSerialization/>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    <wsp:Policy wsu:Id="RespondingGateway_XDR_Binding_Soap_Output_Policy">
        <wsp:ExactlyOne>
            <wsp:All>
                <wsoma:OptimizedMimeSerialization/>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>

    <plnk:partnerLinkType name="EntityXDRSecured">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes.
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="EntityXDRSecuredPortTypeRole" portType="tns:EntityXDRSecuredPortType"/>
    </plnk:partnerLinkType>
</definitions>





