<?xml version="1.0" encoding="utf-8"?>
<!-- This wsdl file is for an XDS.b Document Repository Actor
     It can be used 'as is' to support Document Repository Transactions
     using Synchronous Web Services.
     The wsdl file can also be used to support the Asynchronous
     Web Services Exchange option.  To do this, you will need to
     'uncomment' all the comment sections below that are labeled
     'SECTION FOR WEB SERVICES EXCHANGE OPTION'                  -->
<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  name="NhincProxyXDRSecured"
  targetNamespace="urn:gov:hhs:fha:nhinc:nhincproxyxdrsecured"
  xmlns="http://schemas.xmlsoap.org/wsdl/"
  xmlns:ihe="urn:ihe:iti:xds-b:2007"
  xmlns:rs="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
    xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop"
   xmlns:sxnmp="http://www.sun.com/wsbpel/2.0/process/executable/SUNExtension/NMProperty"
  xmlns:tns="urn:gov:hhs:fha:nhinc:nhincproxyxdrsecured"
  xmlns:ns1="urn:gov:hhs:fha:nhinc:common:nhinccommonproxy">
    <documentation>IHE XDS.b Document Repository</documentation>
    <types>
        <xsd:schema elementFormDefault="qualified"
      targetNamespace="urn:ihe:iti:xds-b:2007"
      xmlns:ihe="urn:ihe:iti:xds-b:2007">
      <!-- Include the message schema -->
            <xsd:include schemaLocation="../schemas/ihe/XDS.b_DocumentRepository.xsd"/>
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:common:nhinccommonadapter" schemaLocation="../schemas/nhinc/common/NhincCommonAdapter.xsd"/>
        </xsd:schema>
        <xsd:schema elementFormDefault="qualified"
      targetNamespace="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0"
      xmlns:rs="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0">
      <!-- Include the message schema -->
            <xsd:include schemaLocation="../schemas/ebRS/rs.xsd"/>
        </xsd:schema>
    <!-- While no elements are directly used from these schema in the WSDL,
      they need to be present here in order for
      code generating toolkits to work properly -->
        <xsd:schema elementFormDefault="qualified"
      targetNamespace="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0"
      xmlns:lcm="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0">
      <!-- Include the message schema -->
            <xsd:include schemaLocation="../schemas/ebRS/lcm.xsd"/>
        </xsd:schema>
        <xsd:schema elementFormDefault="qualified"
      targetNamespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0"
      xmlns:lcm="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0">
      <!-- Include the message schema -->
            <xsd:include schemaLocation="../schemas/ebRS/rim.xsd"/>
        </xsd:schema>
        <xsd:schema targetNamespace="urn:gov:hhs:fha:nhinc:nhincproxyxdr">
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:common:nhinccommonproxy" schemaLocation="../schemas/nhinc/common/NhincCommonProxy.xsd"/>
        </xsd:schema>
    </types>

    <message name="Proxy_ProvideAndRegisterDocumentSet-b_Message">
        <documentation>Provide and Register Document Set</documentation>
        <part name="body" type="ns1:RespondingGateway_ProvideAndRegisterDocumentSetSecuredRequestType"/>
    </message>
    <message name="Proxy_ProvideAndRegisterDocumentSet-bResponse_Message">
        <documentation>Provide And Register Document Set Response</documentation>
        <part name="body" element="rs:RegistryResponse"/>
    </message>

    <portType name="ProxyXDRSecured_PortType">
        <operation name="Proxy_ProvideAndRegisterDocumentSet-b">
            <input message="tns:Proxy_ProvideAndRegisterDocumentSet-b_Message"
        wsaw:Action="urn:ihe:iti:2007:ProvideAndRegisterDocumentSet-b"/>
            <output message="tns:Proxy_ProvideAndRegisterDocumentSet-bResponse_Message"
        wsaw:Action="Proxy_ProvideAndRegisterDocumentSet-bResponse_Message"/>
        </operation>
    </portType>
    <binding name="ProxyXDRSecured_Binding"
           type="tns:ProxyXDRSecured_PortType">
        <soap:binding style="document"
                    transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="Proxy_ProvideAndRegisterDocumentSet-b">
            <soap:operation soapAction="urn:ihe:iti:2007:ProvideAndRegisterDocumentSet-b"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>

    </binding>

    <service name="ProxyXDRSecured_Service">
        <port name="ProxyXDRSecured_PortType"
          binding="tns:ProxyXDRSecured_Binding">
            <soap:address
         location="http://localhost:${NhincHttpPort}/NhincConnect/NhincProxyXDR"/>
        </port>

    </service>

</definitions>




