<?xml version="1.0" encoding="UTF-8"?>
<definitions name="NhincComponentInternalSubDiscovery201309Orch" targetNamespace="http://j2ee.netbeans.org/wsdl/Interfaces/NhincComponentInternalSubDiscovery201309Orch"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/Interfaces/NhincComponentInternalSubDiscovery201309Orch" xmlns:ns="urn:hl7-org:v3" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/Interfaces/NhincComponentInternalSubDiscovery201309Orch">
            <xsd:import namespace="urn:hl7-org:v3" schemaLocation="../schemas/nhinc/hl7/HL7SubjectDiscoveryMessages.xsd"/>
        </xsd:schema>
    </types>
    <message name="GetRealIdentRequestMessage">
        <part name="GetRealIdentRequest" element="ns:PIXConsumer_PRPA_IN201309UVRequest"/>
    </message>
    <message name="GetRealIdentResponseMessage">
        <part name="GetRealIdentResponse" element="ns:PIXConsumer_PRPA_IN201310UVRequest"/>
    </message>
    <portType name="NhincComponentInternalSubDiscovery201309OrchPortType">
        <operation name="GetRealIdent">
            <input name="GetRealIdentRequest" message="tns:GetRealIdentRequestMessage"/>
            <output name="GetRealIdentResponse" message="tns:GetRealIdentResponseMessage"/>
        </operation>
    </portType>
    <plnk:partnerLinkType name="NhincComponentInternalSubDiscovery201309Orch">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="NhincComponentInternalSubDiscovery201309OrchPortTypeRole" portType="tns:NhincComponentInternalSubDiscovery201309OrchPortType"/>
    </plnk:partnerLinkType>
</definitions>
