<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:tns="urn:gov:hhs:fha:nhinc:nhincproxypatientdiscoveryasyncresp"
   xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
   xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
   xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xmlns:hl7="urn:hl7-org:v3"
   xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
   xmlns:wsaws="http://www.w3.org/2006/05/addressing/wsdl"
   name="NhincProxyPatientDiscoveryAsyncResp"
   targetNamespace="urn:gov:hhs:fha:nhinc:nhincproxypatientdiscoveryasyncresp">
  <wsdl:documentation>
     WSDL for NHINC Proxy interface for Patient Discovery Asynchronous Responses
  </wsdl:documentation>
  <wsdl:types>

    <xsd:schema elementFormDefault="qualified"
                targetNamespace="urn:hl7-org:v3" xmlns:hl7="urn:hl7-org:v3">
      <xsd:include schemaLocation="../schemas/nhinc/hl7/Proxy_PRPA_IN201306UVProxyRequest.xsd"/>
      <xsd:include schemaLocation="../schemas/HL7V3/NE2008/multicacheschemas/MCCI_IN000002UV01.xsd"/>
    </xsd:schema>
  </wsdl:types>

  <wsdl:message name="Proxy_ProcessPatientDiscoveryAsyncRespRequestMessage">
    <wsdl:part name="Proxy_ProcessPatientDiscoveryAsyncRespRequest"
               element="hl7:Proxy_PRPA_IN201306UVProxyRequest"/>
  </wsdl:message>
  <wsdl:message name="Proxy_ProcessPatientDiscoveryAsyncRespResponseMessage">
    <wsdl:part name="Proxy_ProcessPatientDiscoveryAsyncRespResponse"
               element="hl7:MCCI_IN000002UV01"/>
  </wsdl:message>

  <wsdl:portType name="NhincProxyPatientDiscoveryAsyncRespPortType">
    <wsdl:operation name="Proxy_ProcessPatientDiscoveryAsyncResp">
      <wsdl:input name="Proxy_ProcessPatientDiscoveryAsyncRespRequest"
                  message="tns:Proxy_ProcessPatientDiscoveryAsyncRespRequestMessage"
                  wsaw:Action="urn:gov:hhs:fha:nhinc:nhincproxypatientdiscoveryasyncresp:Proxy_ProcessPatientDiscoveryAsyncRespRequest"/>
      <wsdl:output name="Proxy_ProcessPatientDiscoveryAsyncRespResponse"
                   message="tns:Proxy_ProcessPatientDiscoveryAsyncRespResponseMessage"
                   wsaw:Action="urn:gov:hhs:fha:nhinc:nhincproxypatientdiscoveryasyncresp:Proxy_ProcessPatientDiscoveryAsyncRespResponse"/>
    </wsdl:operation>
  </wsdl:portType>

  <wsdl:binding name="NhincProxyPatientDiscoveryAsyncRespBinding"
                type="tns:NhincProxyPatientDiscoveryAsyncRespPortType">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <!--<wsaws:UsingAddressing/>-->
    <wsdl:operation name="Proxy_ProcessPatientDiscoveryAsyncResp">
      <wsdl:input name="Proxy_ProcessPatientDiscoveryAsyncRespRequest" >
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="Proxy_ProcessPatientDiscoveryAsyncRespResponse" >
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="NhincProxyPatientDiscoveryAsyncResp">
    <wsdl:port name="NhincProxyPatientDiscoveryAsyncRespPortType"
               binding="tns:NhincProxyPatientDiscoveryAsyncRespBinding">
      <soap12:address location="http://localhost:${HttpDefaultPort}/Gateway/PatientDiscovery/1_0/MsgProxy/NhincProxyPatientDiscoveryAsyncResp"/>
    </wsdl:port>
  </wsdl:service>

</wsdl:definitions>



