<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="urn:gov:hhs:fha:nhinc:nhinccomponentuddiupdatemanager" xmlns:conninfo="urn:gov:hhs:fha:nhinc:common:connectionmanagerinfo" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/" name="UDDIUpdateManager" targetNamespace="urn:gov:hhs:fha:nhinc:nhinccomponentuddiupdatemanager">
	<types>
		<xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/UDDIUpdateManager">
			<xsd:import namespace="urn:gov:hhs:fha:nhinc:common:connectionmanagerinfo" schemaLocation="../schemas/nhinc/common/ConnectionManagerInfo.xsd"/>
		</xsd:schema>
	</types>
	<message name="UDDIUpdateManagerForceRefreshRequestMessage">
		<part name="UDDIUpdateManagerForceRefreshRequest" element="conninfo:UDDIUpdateManagerForceRefreshRequest"/>
	</message>
	<message name="UDDIUpdateManagerForceRefreshResponseMessage">
		<part name="UDDIUpdateManagerForceRefreshResponse" element="conninfo:UDDIUpdateManagerForceRefreshResponse"/>
	</message>
	<portType name="NhincComponentUDDIUpdateManagerPortType">
		<operation name="ForceRefreshFileFromUDDIServer">
			<input name="ForceRefreshFileFromUDDIServerRequest" message="tns:UDDIUpdateManagerForceRefreshRequestMessage"/>
			<output name="ForceRefreshFileFromUDDIServerResponse" message="tns:UDDIUpdateManagerForceRefreshResponseMessage"/>
		</operation>
	</portType>
	<binding name="NhincComponentUDDIUpdateManagerBindingSoap" type="tns:NhincComponentUDDIUpdateManagerPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="ForceRefreshFileFromUDDIServer">
			<soap:operation soapAction="urn:ForceRefreshFileFromUDDIServer"/>
			<input name="ForceRefreshFileFromUDDIServerRequest">
				<soap:body use="literal"/>
			</input>
			<output name="ForceRefreshFileFromUDDIServerResponse">
				<soap:body use="literal"/>
			</output>
		</operation>
	</binding>
	<service name="NhincComponentUDDIUpdateManager">
		<port name="NhincComponentUDDIUpdateManagerPortSoap" binding="tns:NhincComponentUDDIUpdateManagerBindingSoap">
			<soap:address location="http://localhost:${NhincHttpPort}/NhinConnect/NhincComponentUDDIUpdateManager"/>
		</port>
	</service>
	<plnk:partnerLinkType name="NhincComponentUDDIUpdateManager">
		<!-- A partner link type is automatically generated when a new port 
             type is added. Partner link types are used by BPEL processes. 
             In a BPEL process, a partner link represents the interaction 
             between the BPEL process and a partner service. Each partner 
             link is associated with a partner link type.  A partner link 
             type characterizes the conversational relationship between two 
             services. The partner link type can have one or two roles.-->
		<plnk:role name="NhincComponentUDDIUpdateManagerPortTypeRole" portType="tns:NhincComponentUDDIUpdateManagerPortType"/>
	</plnk:partnerLinkType>
</definitions>
