<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:tns="urn:gov:hhs:fha:nhinc:nhincproxypatientdiscovery" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:hl7="urn:hl7-org:v3" name="NhincProxyPatientDiscovery" targetNamespace="urn:gov:hhs:fha:nhinc:nhincproxypatientdiscovery">
	<wsdl:documentation>
     WSDL for NHINC Proxy interface of Patient Discovery
  </wsdl:documentation>
	<wsdl:types>
		<xsd:schema elementFormDefault="qualified" targetNamespace="urn:hl7-org:v3" xmlns:hl7="urn:hl7-org:v3">
			<xsd:include schemaLocation="../schemas/nhinc/hl7/Proxy_PRPA_IN201305UVProxyRequest.xsd"/>
			<xsd:include schemaLocation="../schemas/HL7V3/NE2008/multicacheschemas/PRPA_IN201306UV02.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="Proxy_PRPA_IN201305UVProxyRequestMessage">
		<wsdl:part name="Proxy_PRPA_IN201305UVProxyRequest" element="hl7:Proxy_PRPA_IN201305UVProxyRequest"/>
	</wsdl:message>
	<wsdl:message name="Proxy_PRPA_IN201306UVProxyResponseMessage">
		<wsdl:part name="Proxy_PRPA_IN201306UVProxyResponse" element="hl7:PRPA_IN201306UV02"/>
	</wsdl:message>
	<wsdl:portType name="NhincProxyPatientDiscoveryPortType">
		<wsdl:operation name="Proxy_PRPA_IN201305UV">
			<wsdl:input name="Proxy_PRPA_IN201305UVProxyRequest" message="tns:Proxy_PRPA_IN201305UVProxyRequestMessage" wsaw:Action="urn:gov:hhs:fha:nhinc:nhincproxypatientdiscovery:Proxy_PRPA_IN201305UVProxyRequest"/>
			<wsdl:output name="Proxy_PRPA_IN201306UVProxyResponse" message="tns:Proxy_PRPA_IN201306UVProxyResponseMessage" wsaw:Action="urn:gov:hhs:fha:nhinc:nhincproxypatientdiscovery:Proxy_PRPA_IN201306UVProxyResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="NhincProxyPatientDiscoveryBinding" type="tns:NhincProxyPatientDiscoveryPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="Proxy_PRPA_IN201305UV">
			<soap:operation soapAction="urn:Proxy_PRPA_IN201305UV"/>
			<wsdl:input name="Proxy_PRPA_IN201305UVProxyRequest">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="Proxy_PRPA_IN201306UVProxyResponse">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="NhincProxyPatientDiscovery">
		<wsdl:port name="NhincProxyPatientDiscoveryPort" binding="tns:NhincProxyPatientDiscoveryBinding">
			<soap:address location="http://localhost:${HttpDefaultPort}/Gateway/PatientDiscovery/1_0/MsgProxy/NhincProxyPatientDiscovery"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
