<?xml version="1.0" encoding="UTF-8"?>
<!--
  Deferred Queue Manager WSDL
  -->
<definitions name="DeferredQueueManager" 
    targetNamespace="urn:gov:hhs:fha:nhinc:deferredqueuemanager"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:tns="urn:gov:hhs:fha:nhinc:deferredqueuemanager" 
    xmlns:defq="urn:gov:hhs:fha:nhinc:common:deferredqueuemanager" 
    xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" 
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    >
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/DeferredQueueManager">
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:common:deferredqueuemanager" schemaLocation="../schemas/nhinc/common/DeferredQueueManager.xsd"/>
        </xsd:schema>
    </types>
    <message name="DeferredQueueManagerForceProcessRequestMessage">
        <part name="DeferredQueueManagerForceProcessRequest" element="defq:DeferredQueueManagerForceProcessRequest"/>
    </message>
    <message name="DeferredQueueManagerForceProcessResponseMessage">
        <part name="DeferredQueueManagerForceProcessResponse" element="defq:DeferredQueueManagerForceProcessResponse"/>
    </message>
    
    <portType name="DeferredQueueManagerPortType">
        <operation name="ForceProcessOnDeferredQueue">
            <input name="ForceProcessOnDeferredQueueRequest" message="tns:DeferredQueueManagerForceProcessRequestMessage"/>
            <output name="ForceProcessOnDeferredQueueResponse" message="tns:DeferredQueueManagerForceProcessResponseMessage"/>
        </operation>
    </portType>
    
    <binding name="DeferredQueueManagerBinding" type="tns:DeferredQueueManagerPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="ForceProcessOnDeferredQueue">
            <soap:operation soapAction="urn:ForceProcessOnDeferredQueue"/>
            <input name="ForceProcessOnDeferredQueueRequest">
                <soap:body use="literal"/>
            </input>
            <output name="ForceProcessOnDeferredQueueResponse">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    
    <service name="DeferredQueueManager">
        <port name="DeferredQueueManagerPort" binding="tns:DeferredQueueManagerBinding">
            <soap:address location="http://localhost:${NhincHttpPort}/NhinConnect/DeferredQueueManager"/>
        </port>
    </service>
    
    <plnk:partnerLinkType name="DeferredQueueManager">
        <!-- A partner link type is automatically generated when a new port 
             type is added. Partner link types are used by BPEL processes. 
             In a BPEL process, a partner link represents the interaction 
             between the BPEL process and a partner service. Each partner 
             link is associated with a partner link type.  A partner link 
             type characterizes the conversational relationship between two 
             services. The partner link type can have one or two roles.-->
        <plnk:role name="DeferredQueueManagerPortTypeRole" portType="tns:DeferredQueueManagerPortType"/>
    </plnk:partnerLinkType>
</definitions>
