<?xml version="1.0" encoding="UTF-8"?>
<definitions name="NhincAuditLogQuery" targetNamespace="urn:gov:hhs:fha:nhinc:nhincauditlogquery"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:tns="urn:gov:hhs:fha:nhinc:nhincauditlogquery" 
    xmlns:audit="http://nhinc.services.com/schema/auditmessage" 
    xmlns:nccommoninternalorch="urn:gov:hhs:fha:nhinc:common:nhinccommoninternalorch" 
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <types>
        <xsd:schema targetNamespace="urn:gov:hhs:fha:nhinc:nhincauditlogquery">
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:common:nhinccommoninternalorch" schemaLocation="../schemas/nhinc/common/NhincCommonInternalOrch.xsd"/>
            <xsd:import namespace="http://nhinc.services.com/schema/auditmessage" schemaLocation="../schemas/ihe/auditmessage.xsd"/>
        </xsd:schema>
    </types>
    <message name="NhincAuditLogQueryRequestMessage">
        <part name="NhincAuditLogQueryRequest" element="nccommoninternalorch:FindAuditEventsRequest"/>
    </message>
    <message name="NhincAuditLogQueryResponseMessage">
        <part name="NhincAuditLogQueryResponse" element="audit:FindAuditEventsResponse"/>
    </message>
    <portType name="NhincAuditLogQueryPortType">
        <operation name="NhincAuditLogQuery">
            <input name="NhincAuditLogQueryRequest" message="tns:NhincAuditLogQueryRequestMessage"/>
            <output name="NhincAuditLogQueryResponse" message="tns:NhincAuditLogQueryResponseMessage"/>
        </operation>
    </portType>
    <binding name="NhincAuditLogQueryPortTypeBinding" type="tns:NhincAuditLogQueryPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="NhincAuditLogQuery">
            <soap:operation soapAction="urn:NhincAuditLogQuery"/>
            <input name="NhincAuditLogQueryRequest">
                <soap:body use="literal"/>
            </input>
            <output name="NhincAuditLogQueryResponse">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="NhincAuditLogQueryService">
        <port name="NhincAuditLogcQueryPortTypeBindingPort" binding="tns:NhincAuditLogQueryPortTypeBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/NhinConnect/NhincAuditLogQuery"/>
        </port>
    </service>
    <plnk:partnerLinkType name="NhincAuditLogQuery">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="NhincAuditLogQueryPortTypeRole" portType="tns:NhincAuditLogQueryPortType"/>
    </plnk:partnerLinkType>
</definitions>
