<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:tns="urn:gov:hhs:fha:nhinc:adapterpatientdiscoveryasyncreqqueue" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:hl7="urn:hl7-org:v3" xmlns:wsaws="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:nccommonadapter="urn:gov:hhs:fha:nhinc:common:nhinccommonadapter" name="AdapterPatientDiscoveryAsyncReqQueue" targetNamespace="urn:gov:hhs:fha:nhinc:adapterpatientdiscoveryasyncreqqueue">
	<wsdl:documentation>
     WSDL for Adapter Interface for a Queue for Patient Discovery Asynchronous Requests
    </wsdl:documentation>
	<wsdl:types>
		<xsd:schema elementFormDefault="qualified" targetNamespace="urn:hl7-org:v3" xmlns:hl7="urn:hl7-org:v3">
			<xsd:include schemaLocation="../schemas/nhinc/hl7/HL7PatientDiscoveryMessages.xsd"/>
			<xsd:include schemaLocation="../schemas/HL7V3/NE2008/multicacheschemas/MCCI_IN000002UV01.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="AddPatientDiscoveryAsyncReqRequestMessage">
		<wsdl:part name="AddPatientDiscoveryAsyncReqAsyncRequest" element="hl7:RespondingGateway_PRPA_IN201305UV02Request"/>
	</wsdl:message>
	<wsdl:message name="AddPatientDiscoveryAsyncReqResponseMessage">
		<wsdl:part name="AddPatientDiscoveryAsyncReqAsyncResponse" element="hl7:MCCI_IN000002UV01"/>
	</wsdl:message>
	<wsdl:portType name="AdapterPatientDiscoveryAsyncReqQueuePortType">
		<wsdl:operation name="AddPatientDiscoveryAsyncReq">
			<wsdl:input name="AddPatientDiscoveryAsyncReqAsyncRequest" message="tns:AddPatientDiscoveryAsyncReqRequestMessage" wsaw:Action="urn:gov:hhs:fha:nhinc:adapterpatientdiscoveryasyncreqqueue:AddPatientDiscoveryAsyncReqAsyncRequest"/>
			<wsdl:output name="AddPatientDiscoveryAsyncReqAsyncResponse" message="tns:AddPatientDiscoveryAsyncReqResponseMessage" wsaw:Action="urn:gov:hhs:fha:nhinc:adapterpatientdiscoveryasyncreqqueue:AddPatientDiscoveryAsyncReqAsyncResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="AdapterPatientDiscoveryAsyncReqQueueBindingSoap" type="tns:AdapterPatientDiscoveryAsyncReqQueuePortType">
		<soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="AddPatientDiscoveryAsyncReq">
			<soap12:operation soapAction="urn:AddPatientDiscoveryAsyncReq"/>
			<wsdl:input name="AddPatientDiscoveryAsyncReqAsyncRequest">
				<soap12:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="AddPatientDiscoveryAsyncReqAsyncResponse">
				<soap12:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="AdapterPatientDiscoveryAsyncReqQueue">
		<wsdl:port name="AdapterPatientDiscoveryAsyncReqQueuePortSoap" binding="tns:AdapterPatientDiscoveryAsyncReqQueueBindingSoap">
			<soap12:address location="http://localhost/NhinConnect/AdapterPatientDiscoveryAsyncReqQueue"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
