<?xml version="1.0" encoding="UTF-8"?>
<definitions name="EntityComponentInternalUnsubscribeOrch" targetNamespace="urn:gov:hhs:fha:nhinc:entitycomponentinternalunsubscribeorch"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:tns="urn:gov:hhs:fha:nhinc:entitycomponentinternalunsubscribeorch" 
    xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" 
    xmlns:entintunsub="urn:gov:hhs:fha:nhinc:common:nhinccommoninternalorch" 
    xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema targetNamespace="urn:gov:hhs:fha:nhinc:entitycomponentinternalunsubscribeorch">
            <xsd:import namespace="http://docs.oasis-open.org/wsn/b-2" schemaLocation="../schemas/docs.oasis-open.org/wsn/b-2.xsd"/>
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:common:nhinccommoninternalorch" schemaLocation="../schemas/nhinc/common/NhincCommonInternalOrch.xsd"/>
        </xsd:schema>
    </types>
    <message name="UnsubscribeRequest">
        <part name="UnsubscribeRequest" element="entintunsub:UnsubscribeRequest"/>
    </message>
    <message name="UnsubscribeResponse">
        <part name="UnsubscribeResponse" element="wsnt:UnsubscribeResponse"/>
    </message>
    <portType name="EntityComponentInternalUnsubscribeOrchPortType">
        <operation name="Unsubscribe">
            <input name="UnsubscribeRequest" message="tns:UnsubscribeRequest"/>
            <output name="UnsubscribeResponse" message="tns:UnsubscribeResponse"/>
        </operation>
    </portType>
    <binding name="EntityComponentInternalUnsubscribeOrchPortTypeBinding" type="tns:EntityComponentInternalUnsubscribeOrchPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="Unsubscribe">
            <soap:operation soapAction="urn:EntityComponentInternalUnsubscribeOrchService"/>
            <input name="UnsubscribeRequest">
                <soap:body use="literal"/>
            </input>
            <output name="UnsubscribeResponse">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="EntityComponentInternalUnsubscribeOrchService">
        <port name="EntityComponentInternalUnsubscribeOrchPortTypeBindingPort" binding="tns:EntityComponentInternalUnsubscribeOrchPortTypeBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/NhinConnect/EntityComponentInternalUnsubscribeOrch"/>
        </port>
    </service>
    <plnk:partnerLinkType name="EntityComponentInternalUnsubscribeOrch">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="EntityComponentInternalUnsubscribeOrchPortTypeRole" portType="tns:EntityComponentInternalUnsubscribeOrchPortType"/>
    </plnk:partnerLinkType>
</definitions>
