<?xml version="1.0" encoding="UTF-8"?>
<definitions name="EntityComponentInternalCdcSubscribeOrch" targetNamespace="urn:gov:hhs:fha:nhinc:entitycomponentinternalcdcsubscribeorch"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:tns="urn:gov:hhs:fha:nhinc:entitycomponentinternalcdcsubscribeorch" 
    xmlns:nccommonentity="urn:gov:hhs:fha:nhinc:common:nhinccommonentity" 
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <types>
        <xsd:schema targetNamespace="urn:gov:hhs:fha:nhinc:entitycomponentinternalcdcsubscribeorch">
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:common:nhinccommonentity" schemaLocation="../schemas/nhinc/common/NhincCommonEntity.xsd"/>
        </xsd:schema>
    </types>
    <message name="CdcSubscribeDocumentRequestMessage">
        <part name="CdcSubscribeDocumentRequest" element="nccommonentity:SubscribeCdcBioPackageRequest"/>
    </message>
    <message name="CdcSubscribeDocumentResponseMessage">
        <part name="CdcSubscribeDocumentResponse" element="nccommonentity:SubscribeCdcBioPackageResponse"/>
    </message>
    <portType name="EntityComponentInternalCdcSubscribeOrchPortType">
        <operation name="CdcSubscribeDocument">
            <input name="CdcSubscribeDocumentRequest" message="tns:CdcSubscribeDocumentRequestMessage"/>
            <output name="CdcSubscribeDocumentResponse" message="tns:CdcSubscribeDocumentResponseMessage"/>
        </operation>
    </portType>
    <binding name="EntityComponentInternalCdcSubscribeOrchPortTypeBinding" type="tns:EntityComponentInternalCdcSubscribeOrchPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="CdcSubscribeDocument">
            <soap:operation soapAction="urn:CdcSubscribeDocument"/>
            <input name="CdcSubscribeDocumentRequest">
                <soap:body use="literal"/>
            </input>
            <output name="CdcSubscribeDocumentResponse">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="EntityComponentInternalCdcSubscribeOrchService">
        <port name="EntityComponentInternalCdcSubscribeOrchPortTypeBindingPort" binding="tns:EntityComponentInternalCdcSubscribeOrchPortTypeBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/NhinConnect/EntityComponentInternalCdcSubscribeOrch"/>
        </port>
    </service>
    <plnk:partnerLinkType name="EntityComponentInternalCdcSubscribeOrch">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="EntityComponentInternalCdcSubscribeOrchPortTypeRole" portType="tns:EntityComponentInternalCdcSubscribeOrchPortType"/>
    </plnk:partnerLinkType>
</definitions>
