<?xml version="1.0" encoding="UTF-8"?>
<definitions name="NhincComponentInternalSubDiscovery201302Orch" 
    targetNamespace="urn:gov:hhs:fha:nhinc:nhinccomponentinternalsubdiscovery201302orch"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:tns="urn:gov:hhs:fha:nhinc:nhinccomponentinternalsubdiscovery201302orch" 
    xmlns:hl7="urn:hl7-org:v3" 
    xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <types>
        <xsd:schema targetNamespace="urn:gov:hhs:fha:nhinc:nhinccomponentinternalsubdiscovery201302orch">
            <xsd:import namespace="urn:hl7-org:v3" schemaLocation="../schemas/nhinc/hl7/HL7SubjectDiscoveryMessages.xsd"/>
            <xsd:import namespace="urn:hl7-org:v3" schemaLocation="../schemas/HL7V3/multicacheschemas/MCCI_IN000002UV01.xsd"/>
        </xsd:schema>
    </types>
    <message name="AnnounceRevisedPatientRequestMessage">
        <part name="AnnounceRevisedPatientRequest" element="hl7:PIXConsumer_PRPA_IN201302UVRequest"/>
    </message>
    <message name="AnnounceRevisedPatientResponseMessage">
        <part name="AnnounceRevisedPatientResponse" element="hl7:MCCI_IN000002UV01"/>
    </message>
    <portType name="NhincComponentInternalSubDiscovery201302OrchPortType">
        <operation name="AnnounceRevisedPatient">
            <input name="AnnounceRevisedPatientRequest" message="tns:AnnounceRevisedPatientRequestMessage"/>
            <output name="AnnounceRevisedPatientResponse" message="tns:AnnounceRevisedPatientResponseMessage"/>
        </operation>
    </portType>
    <binding name="NhincComponentInternalSubDiscovery201302OrchBindingSoap11" type="tns:NhincComponentInternalSubDiscovery201302OrchPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="AnnounceRevisedPatient">
            <soap:operation soapAction="urn:AnnounceRevisedPatient"/>
            <input name="AnnounceRevisedPatientRequest">
                <soap:body use="literal"/>
            </input>
            <output name="AnnounceRevisedPatientResponse">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="NhincComponentInternalSubDiscovery201302Orch">
        <port name="NhincComponentInternalSubDiscovery201302OrchBindingSoap11" 
          binding="tns:NhincComponentInternalSubDiscovery201302OrchBindingSoap11">
            <soap:address 
         location="http://localhost:${HttpDefaultPort}/NhinConnect/NhincComponentInternalSubDiscovery201302Orch" />
        </port>
    </service>
    <plnk:partnerLinkType name="NhincComponentInternalSubDiscovery201302Orch">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="NhincComponentInternalSubDiscovery201302OrchPortTypeRole" portType="tns:NhincComponentInternalSubDiscovery201302OrchPortType"/>
    </plnk:partnerLinkType>
</definitions>
