<?xml version="1.0" encoding="UTF-8"?>
<definitions name="NhincComponentInternalNotificationConsumerOrch" targetNamespace="urn:gov:hhs:fha:nhinc:nhinccomponentinternalnotificationconsumerorch"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:tns="urn:gov:hhs:fha:nhinc:nhinccomponentinternalnotificationconsumerorch" 
    xmlns:nccommon="urn:gov:hhs:fha:nhinc:common:nhinccommon" 
    xmlns:nccommoninternalorch="urn:gov:hhs:fha:nhinc:common:nhinccommoninternalorch" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <types>
        <xsd:schema targetNamespace="urn:gov:hhs:fha:nhinc:nhinccomponentinternalnotificationconsumerorch">
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon" schemaLocation="../schemas/nhinc/common/NhincCommon.xsd"/>
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:common:nhinccommoninternalorch" schemaLocation="../schemas/nhinc/common/NhincCommonInternalOrch.xsd"/>
        </xsd:schema>
    </types>
    <message name="NotifyRequest">
        <part name="NotifyRequest" element="nccommoninternalorch:NotifyRequest"/>
    </message>
    <message name="NotifyResponse">
        <part name="Acknowledgement" element="nccommon:Acknowledgement"/>
    </message>
    <portType name="NhincComponentInternalNotificationConsumerPortType">
        <operation name="Notify">
            <input name="NotifyRequest" message="tns:NotifyRequest"/>
            <output name="NotifyResponse" message="tns:NotifyResponse"/>
        </operation>
    </portType>
    <binding name="NhincComponentInternalNotificationConsumerPortTypeBindingSoap11" type="tns:NhincComponentInternalNotificationConsumerPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="Notify">
            <soap:operation/>
            <input name="NotifyRequest">
                <soap:body use="literal"/>
            </input>
            <output name="NotifyResponse">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="NhincComponentInternalNotificationConsumerService">
        <port name="NhincComponentInternalNotificationConsumerPortTypeBindingPort" binding="tns:NhincComponentInternalNotificationConsumerPortTypeBindingSoap11">
            <soap:address location="http://localhost:${HttpDefaultPort}/NhinConnect/NhincComponentInternalNotificationConsumer"/>
        </port>
    </service>
    <plink:partnerLinkType name="NhincComponentInternalNotificationConsumer">
        <plink:role name="NhincComponentInternalNotificationConsumerPortTypeRole" portType="tns:NhincComponentInternalNotificationConsumerPortType"/>
    </plink:partnerLinkType>
</definitions>
