<?xml version="1.0" encoding="UTF-8"?>
<!--
  Nhinc Proxy Document Retrieve Deferred Response
  -->
<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/"
   xmlns="http://schemas.xmlsoap.org/wsdl/"
   xmlns:tns="urn:gov:hhs:fha:nhinc:nhincproxydocretrieveresponse"
   xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   xmlns:ihe="urn:ihe:iti:xds-b:2007"
   xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
   xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
   xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
   xmlns:wsoma="http://schemas.xmlsoap.org/ws/2004/09/policy/optimizedmimeserialization"
   xmlns:dr="http://www.hhs.gov/healthit/nhin"
   xmlns:nccommonproxy="urn:gov:hhs:fha:nhinc:common:nhinccommonproxy"
   xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
   name="NhincProxyDocRetrieveDeferredResponse"
   targetNamespace="urn:gov:hhs:fha:nhinc:nhincproxydocretrieveresponse">
    <documentation>Nhinc Proxy document retrieve deferred response</documentation>
    <types>
        <xsd:schema>
            <xsd:import namespace="urn:ihe:iti:xds-b:2007"
                        schemaLocation="../schemas/ihe/XDS.b_DocumentRepository.xsd"/>
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:common:nhinccommonproxy"
                        schemaLocation="../schemas/nhinc/common/NhincCommonProxy.xsd"/>
            <xsd:import namespace="http://www.hhs.gov/healthit/nhin"
                        schemaLocation="../schemas/nhin/RetrieveDocument.xsd"/>
        </xsd:schema>
    </types>
    <message name="CrossGatewayRetrieveResponseMessage">
        <part name="CrossGatewayRetrieveResponse"
              element="nccommonproxy:RespondingGateway_CrossGatewayRetrieveResponse"/>
    </message>
    <message name="CrossGatewayRetrieveAcknowledgementMessage">
        <part name="CrossGatewayRetrieveAcknowledgement"
              element="dr:DocRetrieveAcknowledgement"/>
    </message>

    <portType name="NhincProxyDocRetrieveDeferredResponsePortType">
        <operation name="CrossGatewayRetrieveResponse">
            <input name="CrossGatewayRetrieveResponse"
                   message="tns:CrossGatewayRetrieveResponseMessage"
                   wsaw:Action="urn:gov:hhs:fha:nhinc:nhincproxydocretrieveresponse:CrossGatewayRetrieveResponseMessage"/>
            <output name="CrossGatewayRetrieveAcknowledgement"
                    message="tns:CrossGatewayRetrieveAcknowledgementMessage"
                    wsaw:Action="urn:gov:hhs:fha:nhinc:nhincproxydocretrieveresponse:CrossGatewayRetrieveAcknowledgementMessage"/>
        </operation>
    </portType>

    <binding name="NhincProxyDocRetrieveDeferredResponseBindingSoap"
             type="tns:NhincProxyDocRetrieveDeferredResponsePortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsp:PolicyReference URI="#NhincProxyDocRetrievePolicy"/>
        <operation name="CrossGatewayRetrieveResponse">
            <soap:operation soapAction="urn:CrossGatewayRetrieveResponse"/>
            <input name="CrossGatewayRetrieveResponse">
                <soap:body use="literal"/>
            </input>
            <output name="CrossGatewayRetrieveAcknowledgement">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="NhincProxyDocRetrieveDeferredResponse">
        <port name="NhincProxyDocRetrieveDeferredResponsePortSoap"
          binding="tns:NhincProxyDocRetrieveDeferredResponseBindingSoap">
            <soap:address
               location="http://localhost:${HttpDefaultPort}/NhinConnect/NhincProxyDocRetrieveDeferredResponse"/>
        </port>
    </service>
   <wsp:Policy wsu:Id="NhincProxyDocRetrievePolicy">
        <wsp:ExactlyOne>
            <wsp:All>
                <wsoma:OptimizedMimeSerialization/>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
</definitions>
