<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:uddi_api_v3_binding="urn:uddi-org:api_v3_binding"
             xmlns:uddi_custody_v3_binding="urn:uddi-org:custody_v3_binding"
             xmlns:uddi_sub_v3_binding="urn:uddi-org:sub_v3_binding"
	     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	     targetNamespace="urn:uddi-org:v3_service">
                 <!-- 
	Copyright (c) OASIS Open 2002-2004. All Rights Reserved.

	Version 3.0.2 
	-->
	<documentation>WSDL service definition for UDDI 3.0.2 JAX-RPC client</documentation>

    <import namespace="urn:uddi-org:api_v3_binding" location="uddi_api_v3_binding.wsdl"/>
    <import namespace="urn:uddi-org:custody_v3_binding" location="uddi_custody_v3_binding.wsdl"/>
    <import namespace="urn:uddi-org:sub_v3_binding" location="uddi_sub_v3_binding.wsdl"/>

    <service name="UDDI_Service">
        <port name="UDDI_Inquiry_Port" binding="uddi_api_v3_binding:UDDI_Inquiry_SoapBinding">
            <soap:address location="http://localhost/uddi/inquire/"/>
        </port>
        <port name="UDDI_Publication_Port" binding="uddi_api_v3_binding:UDDI_Publication_SoapBinding">
            <soap:address location="http://localhost/uddi/publish/"/>
        </port>
        <port name="UDDI_Security_Port" binding="uddi_api_v3_binding:UDDI_Security_SoapBinding">
            <soap:address location="http://localhost/uddi/security/"/>
        </port>
        <port name="UDDI_Custody_Port" binding="uddi_custody_v3_binding:UDDI_CustodyTransfer_SoapBinding">
            <soap:address location="http://localhost/uddi/custody/"/>
        </port>
        <port name="UDDI_Subscription_Port" binding="uddi_sub_v3_binding:UDDI_Subscription_SoapBinding">
            <soap:address location="http://localhost/uddi/subscription/"/>
        </port>
    </service>

	
</definitions>
