<?xml version="1.0" encoding="UTF-8"?>
<definitions name="AdapterMpiManager" targetNamespace="urn:gov:hhs:fha:nhinc:adaptermpimanager"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:tns="urn:gov:hhs:fha:nhinc:adaptermpimanager" 
    xmlns:hl7="urn:hl7-org:v3" 
    xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema targetNamespace="urn:gov:hhs:fha:nhinc:adaptermpimanager">
            <xsd:import namespace="urn:hl7-org:v3" schemaLocation="../schemas/HL7V3/NE2008/multicacheschemas/MCCI_IN000002UV01.xsd"/>
            <xsd:import namespace="urn:hl7-org:v3" schemaLocation="../schemas/HL7V3/NE2008/multicacheschemas/PRPA_IN201301UV02.xsd"/>
        </xsd:schema>
    </types>
    <message name="AddPatientRequestMessage">
        <part name="AddPatientRequest" element="hl7:PRPA_IN201301UV02"/>
    </message>
    <message name="AddPatientResponseMessage">
        <part name="AddPatientResponse" element="hl7:MCCI_IN000002UV01"/>
    </message>
    
    <portType name="AdapterMpiManagerPortType">
        <operation name="AddPatient">
            <input name="AddPatientRequest" message="tns:AddPatientRequestMessage"/>
            <output name="AddPatientResponse" message="tns:AddPatientResponseMessage"/>
        </operation>
        
    </portType>
    <binding name="AdapterMpiManagerPortTypeBinding" type="tns:AdapterMpiManagerPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="AddPatient">
            <soap:operation style="document" soapAction="urn:AddPatient"/>
            <input name="AddPatientRequest">
                <soap:body use="literal"/>
            </input>
            <output name="AddPatientResponse">
                <soap:body use="literal"/>
            </output>
        </operation>
       
    </binding>
    <service name="AdapterMpiManagerService">
        <port name="AdapterMpiManagerPortTypeBindingPort" binding="tns:AdapterMpiManagerPortTypeBinding">
            <soap:address location="http://localhost:${NhincHttpPort}/AdapterMpiManagerService"/>
        </port>
    </service>
    <plnk:partnerLinkType name="AdapterMpiManager">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="AdapterMpiManagerPortTypeRole" portType="tns:AdapterMpiManagerPortType"/>
    </plnk:partnerLinkType>
</definitions>
