
package gov.hhs.fha.nhinc.adapter.commondatalayer;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3.1-hudson-749-SNAPSHOT
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DODConnectorService", targetNamespace = "urn:gov:hhs:fha:nhinc:adapter:commondatalayer", wsdlLocation = "file:/C:/projects/DODConnector/src/java/DODConnector.wsdl")
public class DODConnectorService
    extends Service
{

    private final static URL DODCONNECTORSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(gov.hhs.fha.nhinc.adapter.commondatalayer.DODConnectorService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = gov.hhs.fha.nhinc.adapter.commondatalayer.DODConnectorService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/projects/DODConnector/src/java/DODConnector.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/projects/DODConnector/src/java/DODConnector.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DODCONNECTORSERVICE_WSDL_LOCATION = url;
    }

    public DODConnectorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DODConnectorService() {
        super(DODCONNECTORSERVICE_WSDL_LOCATION, new QName("urn:gov:hhs:fha:nhinc:adapter:commondatalayer", "DODConnectorService"));
    }

    /**
     * 
     * @return
     *     returns DoDConnectorPortType
     */
    @WebEndpoint(name = "CommonDataLayerPort")
    public DODConnectorPortType getCommonDataLayerPort() {
        return super.getPort(new QName("urn:gov:hhs:fha:nhinc:adapter:commondatalayer", "CommonDataLayerPort"), DODConnectorPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DoDConnectorPortType
     */
    @WebEndpoint(name = "CommonDataLayerPort")
    public DODConnectorPortType getCommonDataLayerPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:gov:hhs:fha:nhinc:adapter:commondatalayer", "CommonDataLayerPort"), DODConnectorPortType.class, features);
    }

}
