<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="urn:uddi-org:repl_v3_portType" xmlns:uddi_repl="urn:uddi-org:repl_v3" xmlns:uddi="urn:uddi-org:api_v3" targetNamespace="urn:uddi-org:repl_v3_portType">
	<!-- 
	Copyright (c) 2000-2002 by Accenture, Ariba, Inc., Commerce One, Inc. Fujitsu Limited, Hewlett-Packard Company, i2 Technologies, Inc., Intel Corporation, 
	International Business Machines Corporation, Microsoft Corporation, Oracle Corporation, SAP AG, Sun Microsystems, Inc., and VeriSign, Inc.  All Rights Reserved.
	
	Copyright (c) OASIS Open 2002-2004. All Rights Reserved.
	Version 3.0.2 
	-->
	<documentation>
	                This WSDL document defines the portTypes for the UDDI V3 Replication API Set.
	</documentation>
	<types>
		<xsd:schema targetNamespace="urn:uddi-org:repl_v3_portType" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:uddi-org:api_v3" schemaLocation="../schemas/uddi/uddi_v3.xsd"/>
			<xsd:import namespace="urn:uddi-org:repl_v3" schemaLocation="../schemas/uddi/uddi_v3replication.xsd"/>
		</xsd:schema>
	</types>
	<message name="changeRecordsMessage">
		<part name="body" element="uddi_repl:changeRecords"/>
	</message>
	<message name="dispositionReportFaultMessage">
		<part name="body" element="uddi:dispositionReport"/>
	</message>
	<message name="successMessage"/>
	<message name="do_pingMessage">
		<part name="body" element="uddi_repl:do_ping"/>
	</message>
	<message name="get_changeRecordsMessage">
		<part name="body" element="uddi_repl:get_changeRecords"/>
	</message>
	<message name="get_highWaterMarksMessage">
		<part name="body" element="uddi_repl:get_highWaterMarks"/>
	</message>
	<message name="highWaterMarksMessage">
		<part name="body" element="uddi_repl:highWaterMarks"/>
	</message>
	<message name="notify_changeRecordsAvailableMessage">
		<part name="body" element="uddi_repl:notify_changeRecordsAvailable"/>
	</message>
	<message name="operatorNodeIDMessage">
		<part name="body" element="uddi_repl:operatorNodeID"/>
	</message>
	<message name="transfer_custodyMessage">
		<part name="body" element="uddi_repl:transfer_custody"/>
	</message>
	<portType name="UDDI_Replication_PortType">
		<documentation>This portType defines all of the UDDI replication operations.</documentation>
		<operation name="get_changeRecords">
			<input message="tns:get_changeRecordsMessage"/>
			<output message="tns:changeRecordsMessage"/>
			<fault name="error" message="tns:dispositionReportFaultMessage"/>
		</operation>
		<operation name="notify_changeRecordsAvailable">
			<input message="tns:notify_changeRecordsAvailableMessage"/>
			<output message="tns:successMessage"/>
			<fault name="error" message="tns:dispositionReportFaultMessage"/>
		</operation>
		<operation name="do_ping">
			<input message="tns:do_pingMessage"/>
			<output message="tns:operatorNodeIDMessage"/>
			<fault name="error" message="tns:dispositionReportFaultMessage"/>
		</operation>
		<operation name="get_highWaterMarks">
			<input message="tns:get_highWaterMarksMessage"/>
			<output message="tns:highWaterMarksMessage"/>
			<fault name="error" message="tns:dispositionReportFaultMessage"/>
		</operation>
		<operation name="transfer_custody">
			<input message="tns:transfer_custodyMessage"/>
			<output message="tns:successMessage"/>
			<fault name="error" message="tns:dispositionReportFaultMessage"/>
		</operation>
	</portType>
</definitions>
